// AUTO-GENERATED from public NCAA (D1/D2/D3), NAIA and NJCAA member directories.
// Tuple shape: [name, state, division, commonName?]
export type CollegeTuple = [string, string, string, string?];

export const COLLEGE_TUPLES: CollegeTuple[] = [
  ["Abilene Christian University","TX","D1","Abilene Christian"],
  ["Abraham Baldwin Agricultural College","GA","NAIA"],
  ["Adams State University","CO","D2"],
  ["Adelphi University","NY","D2"],
  ["Adrian College","MI","D3"],
  ["Agnes Scott College","GA","D3"],
  ["Alabama Agricultural and Mechanical University","AL","D1","Alabama A&M"],
  ["Alabama State University","AL","D1","Alabama State"],
  ["Albany State University","GA","D2"],
  ["Albertus Magnus College","CT","D3"],
  ["Albion College","MI","D3"],
  ["Albright College","PA","D3"],
  ["Alcorn State University","MS","D1","Alcorn State"],
  ["Alfred State College","NY","D3"],
  ["Alfred University","NY","D3"],
  ["Allegheny College","PA","D3"],
  ["Allen Community College","KS","JUCO"],
  ["Allen University","SC","D2"],
  ["Alma College","MI","D3"],
  ["Alvernia University","PA","D3"],
  ["Alverno College","WI","D3"],
  ["American International College","MA","D2"],
  ["American University","WA","D1","American"],
  ["Amherst College","MA","D3"],
  ["Anderson University","SC","D2"],
  ["Andrew College","GA","NAIA"],
  ["Angelo State University","TX","D2"],
  ["Appalachian State University","NC","D1","Appalachian State"],
  ["Aquinas College","MI","NAIA"],
  ["Arcadia University","PA","D3"],
  ["Arizona Christian University","AZ","NAIA"],
  ["Arizona State University","AZ","D1","Arizona State"],
  ["Arkansas Baptist College","AR","NAIA"],
  ["Arkansas State University","AR","D1","Arkansas State"],
  ["Arkansas Tech University","AR","D2"],
  ["Asbury University","KY","D3"],
  ["Ashland University","OH","D2"],
  ["Assumption University","MA","D2"],
  ["Auburn University","AL","D1","Auburn"],
  ["Auburn University at Montgomery","AL","D2"],
  ["Augsburg University","MN","D3"],
  ["Augusta University","GA","D2"],
  ["Augustana College","IL","D3"],
  ["Augustana University","SD","D2"],
  ["Aurora University","IL","D3"],
  ["Austin College","TX","D3"],
  ["Austin Peay State University","TN","D1","Austin Peay"],
  ["Ave Maria University","FL","NAIA"],
  ["Averett University","VA","D3"],
  ["Avila University","MO","NAIA"],
  ["Azusa Pacific University","CA","D3"],
  ["Babson College","MA","D3"],
  ["Baker University","KS","NAIA"],
  ["Baldwin Wallace University","OH","D3"],
  ["Ball State University","IN","D1","Ball State"],
  ["Bard College","NY","D3"],
  ["Barry University","FL","D2"],
  ["Barton College","NC","D2"],
  ["Barton Community College","KS","JUCO"],
  ["Baruch College","NY","D3"],
  ["Bates College","ME","D3"],
  ["Batten University","VA","D3"],
  ["Baylor University","TX","D1","Baylor"],
  ["Belhaven University","MS","D3"],
  ["Bellarmine University","KY","D1","Bellarmine"],
  ["Bellevue University","NE","NAIA"],
  ["Belmont Abbey College","NC","D2"],
  ["Belmont University","TN","D1","Belmont"],
  ["Beloit College","WI","D3"],
  ["Bemidji State University","MN","D2"],
  ["Benedict College","SC","D2"],
  ["Benedictine College","KS","NAIA"],
  ["Benedictine University","IL","D3"],
  ["Benedictine University at Mesa","AZ","NAIA"],
  ["Bentley University","MA","D2"],
  ["Berea College","KY","D3"],
  ["Berry College","GA","D3"],
  ["Bethany College","WV","D3"],
  ["Bethany Lutheran College","MN","D3"],
  ["Bethel College (KS)","KS","NAIA"],
  ["Bethel University","MN","D3"],
  ["Bethel University (IN)","IN","NAIA"],
  ["Bethel University (TN)","TN","NAIA"],
  ["Bethune–Cookman University","FL","D1","Bethune–Cookman"],
  ["Biola University","CA","D2"],
  ["Bismarck State College","ND","NAIA"],
  ["Black Hills State University","SD","D2"],
  ["Blackburn College","IL","D3"],
  ["Blue Mountain Christian University","MS","NAIA"],
  ["Bluefield State University","WV","D2"],
  ["Bluefield University","VA","NAIA"],
  ["Bluffton University","OH","D3"],
  ["Boise State University","ID","D1","Boise State"],
  ["Boston College","MA","D1"],
  ["Boston University","MA","D1"],
  ["Bowdoin College","ME","D3"],
  ["Bowie State University","MD","D2"],
  ["Bowling Green State University","OH","D1","Bowling Green"],
  ["Bradley University","IL","D1","Bradley"],
  ["Brandeis University","MA","D3"],
  ["Brenau University","GA","NAIA"],
  ["Brescia University","KY","NAIA"],
  ["Brevard College","NC","D3"],
  ["Brewton–Parker Christian University","GA","NAIA"],
  ["Briar Cliff University","IA","NAIA"],
  ["Bridgewater College","VA","D3"],
  ["Bridgewater State University","MA","D3"],
  ["Brigham Young University","UT","D1","BYU"],
  ["Brooklyn College","NY","D3"],
  ["Brown University","RI","D1","Brown"],
  ["Bryan College","TN","NAIA"],
  ["Bryant University","RI","D1","Bryant"],
  ["Bryn Mawr College","PA","D3"],
  ["Bucknell University","PA","D1","Bucknell"],
  ["Buena Vista University","IA","D3"],
  ["Buffalo State University","NY","D3"],
  ["Bushnell University","OR","NAIA"],
  ["Butler Community College","KS","JUCO"],
  ["Butler University","IN","D1","Butler"],
  ["Cairn University","PA","D3"],
  ["Caldwell University","NJ","D2"],
  ["California Baptist University","CA","D1","Cal Baptist"],
  ["California Institute of Technology","CA","D3"],
  ["California Lutheran University","CA","D3"],
  ["California Polytechnic State University","CA","D1","Cal Poly"],
  ["California State Polytechnic University, Humboldt","CA","D2"],
  ["California State Polytechnic University, Pomona","CA","D2"],
  ["California State University San Marcos","CA","D2"],
  ["California State University, Bakersfield","CA","D1"],
  ["California State University, Chico","CA","D2"],
  ["California State University, Dominguez Hills","CA","D2"],
  ["California State University, East Bay","CA","D2"],
  ["California State University, Fresno","CA","D1","Fresno State"],
  ["California State University, Fullerton","CA","D1","Cal State Fullerton"],
  ["California State University, Long Beach","CA","D1","Long Beach State"],
  ["California State University, Los Angeles","CA","D2"],
  ["California State University, Monterey Bay","CA","D2"],
  ["California State University, Northridge","CA","D1","Cal State Northridge / CSUN"],
  ["California State University, Sacramento","CA","D1","Sacramento State"],
  ["California State University, San Bernardino","CA","D2"],
  ["California State University, Stanislaus","CA","D2"],
  ["Calumet College of St. Joseph (CCSJ)","IN","NAIA"],
  ["Calvin University","MI","D3"],
  ["Cameron University","OK","D2"],
  ["Campbell University","NC","D1","Campbell"],
  ["Campbellsville University","KY","NAIA"],
  ["Canisius University","NY","D1","Canisius"],
  ["Capital University","OH","D3"],
  ["Carleton College","MN","D3"],
  ["Carlow University","PA","D3"],
  ["Carnegie Mellon University","PA","D3"],
  ["Carolina University","NC","NAIA"],
  ["Carroll College","MT","NAIA"],
  ["Carroll University","WI","D3"],
  ["Carson–Newman University","TN","D2"],
  ["Carthage College","WI","D3"],
  ["Case Western Reserve University","OH","D3"],
  ["Catawba College","NC","D2"],
  ["Catholic University of America","WA","D3"],
  ["Cedar Crest College","PA","D3"],
  ["Cedarville University","OH","D2"],
  ["Centenary College of Louisiana","LA","D3"],
  ["Centenary University","NJ","D3"],
  ["Central Baptist College","AR","NAIA"],
  ["Central Christian College of Kansas","KS","NAIA"],
  ["Central College","IA","D3"],
  ["Central Connecticut State University","CT","D1","Central Connecticut"],
  ["Central Methodist University","MO","NAIA"],
  ["Central Michigan University","MI","D1","Central Michigan"],
  ["Central State University","OH","D2"],
  ["Central Washington University","WA","D2"],
  ["Centre College","KY","D3"],
  ["Chadron State College","NE","D2"],
  ["Chaminade University of Honolulu","HI","D2"],
  ["Champion Christian College","AR","NAIA"],
  ["Chapman University","CA","D3"],
  ["Charleston Southern University","SC","D1","Charleston Southern"],
  ["Chatham University","PA","D3"],
  ["Chestnut Hill College","PA","D2"],
  ["Chicago State University","IL","D1","Chicago State"],
  ["Chowan University","NC","D2"],
  ["Christian Brothers University","TN","D2"],
  ["Christopher Newport University","VA","D3"],
  ["City College of New York","NY","D3"],
  ["Claflin University","SC","D2"],
  ["Claremont McKenna College, Harvey Mudd College, and Scripps College","CA","D3"],
  ["Clark Atlanta University","GA","D2"],
  ["Clark University","MA","D3"],
  ["Clarke University","IA","NAIA"],
  ["Clarkson University|group=A|name='MH yes'","NY","D3"],
  ["Clayton State University","GA","D2"],
  ["Cleary University","MI","NAIA"],
  ["Clemson University","SC","D1","Clemson"],
  ["Cleveland State University","OH","D1","Cleveland State"],
  ["Cloud County Community College","KS","JUCO"],
  ["Coastal Carolina University","SC","D1","Coastal Carolina"],
  ["Coe College","IA","D3"],
  ["Coffeyville Community College","KS","JUCO"],
  ["Coker University","SC","D2"],
  ["Colby College","ME","D3"],
  ["Colby Community College","KS","JUCO"],
  ["Colby–Sawyer College","NH","D3"],
  ["Colgate University","NY","D1","Colgate"],
  ["College of Charleston","SC","D1","Charleston"],
  ["College of Coastal Georgia","GA","NAIA"],
  ["College of Idaho","ID","NAIA"],
  ["College of Saint Benedict","MN","D3"],
  ["College of Saint Mary","NE","NAIA"],
  ["College of Staten Island","NY","D2"],
  ["College of Wooster","OH","D3"],
  ["College of the Holy Cross","MA","D1","Holy Cross"],
  ["College of the Ozarks","MO","NAIA"],
  ["Colorado Christian University","CO","D2"],
  ["Colorado College","CO","D3"],
  ["Colorado Mesa University","CO","D2"],
  ["Colorado School of Mines","CO","D2"],
  ["Colorado State University","CO","D1","Colorado State"],
  ["Colorado State University–Pueblo","CO","D2"],
  ["Columbia College (MO)","MO","NAIA"],
  ["Columbia College (SC)","SC","NAIA"],
  ["Columbia International University","SC","NAIA"],
  ["Columbia University in the City of New York","NY","D1","Columbia"],
  ["Columbus State University","GA","D2"],
  ["Commonwealth University-Bloomsburg","PA","D2"],
  ["Commonwealth University-Lock Haven","PA","D2"],
  ["Commonwealth University-Mansfield","PA","D2"],
  ["Concord University","WV","D2"],
  ["Concordia College","MN","D3"],
  ["Concordia University Chicago","IL","D3"],
  ["Concordia University Texas","TX","D3"],
  ["Concordia University Wisconsin","WI","D3"],
  ["Concordia University–Irvine","CA","D2"],
  ["Concordia University–Nebraska","NE","NAIA"],
  ["Concordia University–St. Paul","MN","D2"],
  ["Connecticut College","CT","D3"],
  ["Connors State College","OK","JUCO"],
  ["Converse University","SC","D2"],
  ["Coppin State University","MD","D1","Coppin State"],
  ["Corban University","OR","NAIA"],
  ["Cornell College","IA","D3"],
  ["Cornell University","NY","D1","Cornell"],
  ["Cornerstone University","MI","NAIA"],
  ["Cottey College","NV","NAIA"],
  ["Covenant College","GA","D3"],
  ["Cowley College","KS","JUCO"],
  ["Creighton University","NE","D1","Creighton"],
  ["Crowder College","MO","JUCO"],
  ["Crowley's Ridge College","AR","NAIA"],
  ["Crown College","MN","D3"],
  ["Culver–Stockton College","MO","NAIA"],
  ["Cumberland University","TN","NAIA"],
  ["Curry College","MA","D3"],
  ["D'Youville University","NY","D2"],
  ["Daemen University","NY","D2"],
  ["Dakota State University","SD","NAIA"],
  ["Dakota Wesleyan University","SD","NAIA"],
  ["Dallas Baptist University","TX","D2"],
  ["Dalton State College","GA","NAIA"],
  ["Dartmouth College","NH","D1","Dartmouth"],
  ["Davenport University","MI","D2"],
  ["Davidson College","NC","D1","Davidson"],
  ["Davis & Elkins College","WV","D2"],
  ["DePaul University","IL","D1","DePaul"],
  ["DePauw University","IN","D3"],
  ["DeSales University","PA","D3"],
  ["Dean College","MA","D3"],
  ["Defiance College","OH","NAIA"],
  ["Delaware State University","DE","D1","Delaware State"],
  ["Delaware Valley University","PA","D3"],
  ["Delta State University","MS","D2"],
  ["Denison University","OH","D3"],
  ["Dickinson College","PA","D3"],
  ["Dickinson State University","ND","NAIA"],
  ["Dillard University","LA","NAIA"],
  ["Doane College","NE","NAIA"],
  ["Dodge City Community College","KS","JUCO"],
  ["Dominican University","IL","D3"],
  ["Dominican University New York","NY","D2"],
  ["Dominican University of California","CA","D2"],
  ["Dordt University","IA","NAIA"],
  ["Drake University","IA","D1","Drake"],
  ["Drew University","NJ","D3"],
  ["Drexel University","PA","D1","Drexel"],
  ["Drury University","MO","D2"],
  ["Duke University","NC","D1","Duke"],
  ["Duquesne University of the Holy Spirit","PA","D1","Duquesne"],
  ["Earlham College","IN","D3"],
  ["East Carolina University","NC","D1","East Carolina"],
  ["East Central University","OK","D2"],
  ["East Stroudsburg University","PA","D2"],
  ["East Tennessee State University","TN","D1","East Tennessee State"],
  ["East Texas A&M University","TX","D1","East Texas A&M"],
  ["East Texas Baptist University","TX","D3"],
  ["Eastern Connecticut State University","CT","D3"],
  ["Eastern Illinois University","IL","D1","Eastern Illinois"],
  ["Eastern Kentucky University","KY","D1","Eastern Kentucky"],
  ["Eastern Mennonite University","VA","D3"],
  ["Eastern Michigan University","MI","D1","Eastern Michigan"],
  ["Eastern New Mexico University","NM","D2"],
  ["Eastern Oklahoma State College","OK","JUCO"],
  ["Eastern Oregon University","OR","NAIA"],
  ["Eastern University","PA","D3"],
  ["Eastern Washington University","WA","D1","Eastern Washington"],
  ["Eckerd College","FL","D2"],
  ["Edgewood University","WI","D3"],
  ["Edward Waters University","FL","D2"],
  ["Elizabeth City State University","NC","D2"],
  ["Elizabethtown College","PA","D3"],
  ["Elmhurst University","IL","D3"],
  ["Elmira College","NY","D3"],
  ["Elms College","MA","D3"],
  ["Elon University","NC","D1","Elon"],
  ["Embry–Riddle Aeronautical University","FL","D2"],
  ["Embry–Riddle Aeronautical University, Prescott","AZ","NAIA"],
  ["Emerson College","MA","D3"],
  ["Emmanuel College","MA","D3"],
  ["Emmanuel University","GA","D2"],
  ["Emory & Henry University","VA","D2"],
  ["Emory University","GA","D3"],
  ["Emporia State University","KS","D2"],
  ["Endicott College","MA","D3"],
  ["Erskine College","SC","D2"],
  ["Eureka College","IL","D3"],
  ["Eutectics","MO","NAIA"],
  ["Evangel University","MO","NAIA"],
  ["Fairfield University","CT","D1","Fairfield"],
  ["Fairleigh Dickinson University","NJ","D1","Fairleigh Dickinson"],
  ["Fairleigh Dickinson University, Florham","NJ","D3"],
  ["Fairmont State University","WV","D2"],
  ["Farmingdale State College","NY","D3"],
  ["Faulkner University","AL","NAIA"],
  ["Fayetteville State University","NC","D2"],
  ["Felician University","NJ","D2"],
  ["Ferris State University","MI","D2"],
  ["Ferrum College","VA","D2"],
  ["Fisher College","MA","NAIA"],
  ["Fisk University","TN","NAIA"],
  ["Fitchburg State University","MA","D3"],
  ["Flagler College","FL","D2"],
  ["Florida Agricultural and Mechanical University","FL","D1","Florida A&M"],
  ["Florida Atlantic University","FL","D1","Florida Atlantic"],
  ["Florida College","FL","NAIA"],
  ["Florida Gulf Coast University","FL","D1","FGCU"],
  ["Florida Institute of Technology","FL","D2"],
  ["Florida International University","FL","D1","FIU"],
  ["Florida Memorial University","FL","NAIA"],
  ["Florida National University","FL","NAIA"],
  ["Florida Southern College","FL","D2"],
  ["Florida State University","FL","D1","Florida State"],
  ["Fordham University","NY","D1","Fordham"],
  ["Fort Hays State University","KS","D2"],
  ["Fort Lewis College","CO","D2"],
  ["Fort Scott Community College","KS","JUCO"],
  ["Fort Valley State University","GA","D2"],
  ["Framingham State University","MA","D3"],
  ["Francis Marion University","SC","D2"],
  ["Franciscan University of Steubenville","OH","D3"],
  ["Franklin & Marshall College","PA","D3"],
  ["Franklin College","IN","D3"],
  ["Franklin Pierce University","NH","D2"],
  ["Freed–Hardeman University","TN","NAIA"],
  ["Fresno Pacific University","CA","D2"],
  ["Friends University","KS","NAIA"],
  ["Frostburg State University","MD","D2"],
  ["Furman University","SC","D1","Furman"],
  ["Gallaudet University","WA","D3"],
  ["Gannon University","PA","D2"],
  ["Garden City Community College","KS","JUCO"],
  ["Gardner–Webb University","NC","D1","Gardner–Webb"],
  ["Geneva College","PA","D3"],
  ["George Fox University","OR","D3"],
  ["George Mason University","VA","D1","George Mason"],
  ["Georgetown College","KY","NAIA"],
  ["Georgetown University","WA","D1","Georgetown"],
  ["Georgia College & State University","GA","D2"],
  ["Georgia Gwinnett College","GA","NAIA"],
  ["Georgia Institute of Technology","GA","D1","Georgia Tech"],
  ["Georgia Southern University","GA","D1","Georgia Southern"],
  ["Georgia Southern University–East Georgia Campus","GA","NAIA"],
  ["Georgia Southwestern State University","GA","D2"],
  ["Georgia State University","GA","D1","Georgia State"],
  ["Georgian Court University","NJ","D2"],
  ["Gettysburg College","PA","D3"],
  ["Glenville State University","WV","D2"],
  ["Goldey–Beacom College","DE","D2"],
  ["Gonzaga University","WA","D1","Gonzaga"],
  ["Gordon College","MA","D3"],
  ["Goshen College","IN","NAIA"],
  ["Goucher College","MD","D3"],
  ["Governors State University","IL","NAIA"],
  ["Grace College & Seminary","IN","NAIA"],
  ["Graceland University","IA","NAIA"],
  ["Grambling State University","LA","D1","Grambling State"],
  ["Grand Canyon University","AZ","D1","Grand Canyon"],
  ["Grand Valley State University","MI","D2"],
  ["Grand View University","IA","NAIA"],
  ["Greensboro College","NC","D3"],
  ["Greenville University","IL","D3"],
  ["Grinnell College","IA","D3"],
  ["Grove City College","PA","D3"],
  ["Guilford College","NC","D3"],
  ["Gustavus Adolphus College","MN","D3"],
  ["Gwynedd Mercy University","PA","D3"],
  ["Hamilton College","NY","D3"],
  ["Hamline University","MN","D3"],
  ["Hampden–Sydney College","VA","D3"],
  ["Hampton University","VA","D1","Hampton"],
  ["Hannibal–LaGrange University","MO","NAIA"],
  ["Hanover College","IN","D3"],
  ["Harding University","AR","D2"],
  ["Hardin–Simmons University","TX","D3"],
  ["Harris–Stowe State University","MO","NAIA"],
  ["Hartwick College","NY","D3"],
  ["Harvard University","MA","D1","Harvard"],
  ["Haskell Indian Nations University","KS","NAIA"],
  ["Hastings College","NE","NAIA"],
  ["Haverford College","PA","D3"],
  ["Hawai'i Pacific University","HI","D2"],
  ["Heidelberg University","OH","D3"],
  ["Henderson State University","AR","D2"],
  ["Hendrix College","AR","D3"],
  ["Hesston College","KS","NAIA"],
  ["High Point University","NC","D1","High Point"],
  ["Highland Community College","KS","JUCO"],
  ["Hilbert College","NY","D3"],
  ["Hillsdale College","MI","D2"],
  ["Hiram College","OH","D3"],
  ["Hobart College","NY","D3"],
  ["Hofstra University","NY","D1","Hofstra"],
  ["Hollins University","VA","D3"],
  ["Holy Cross College","IN","NAIA"],
  ["Holy Family University","PA","D2"],
  ["Hood College","MD","D3"],
  ["Hope College","MI","D3"],
  ["Hope International University","CA","NAIA"],
  ["Houghton University","NY","D3"],
  ["Houston Christian University","TX","D1","Houston Christian"],
  ["Howard Payne University","TX","D3"],
  ["Howard University","WA","D1","Howard"],
  ["Hunter College","NY","D3"],
  ["Huntingdon College","AL","D3"],
  ["Huntington University","IN","NAIA"],
  ["Husson University","ME","D3"],
  ["Huston–Tillotson University","TX","NAIA"],
  ["Hutchinson Community College","KS","JUCO"],
  ["Idaho State University","ID","D1","Idaho State"],
  ["Illinois College","IL","D3"],
  ["Illinois Institute of Technology","IL","D3"],
  ["Illinois State University","IL","D1","Illinois State"],
  ["Illinois Wesleyan University","IL","D3"],
  ["Immaculata University","PA","D3"],
  ["Independence Community College","KS","JUCO"],
  ["Indian Hills Community College","IA","JUCO"],
  ["Indiana Institute of Technology (Indiana Tech)","IN","NAIA"],
  ["Indiana State University","IN","D1","Indiana State"],
  ["Indiana University Bloomington","IN","D1","Indiana"],
  ["Indiana University Columbus (IU Columbus)","IN","NAIA"],
  ["Indiana University East (IU East)","IN","NAIA"],
  ["Indiana University Indianapolis","IN","D1","IU Indy"],
  ["Indiana University Kokomo (IU Kokomo)","IN","NAIA"],
  ["Indiana University Northwest (IU Northwest)","IN","NAIA"],
  ["Indiana University South Bend (IU South Bend)","IN","NAIA"],
  ["Indiana University Southeast (IU Southeast or IUS)","IN","NAIA"],
  ["Indiana University of Pennsylvania","IN","D2"],
  ["Indiana Wesleyan University","IN","NAIA"],
  ["Iona University","NY","D1","Iona"],
  ["Iowa State University of Science and Technology","IA","D1","Iowa State"],
  ["Iowa Western Community College","IA","JUCO"],
  ["Ithaca College","NY","D3"],
  ["Jackson State University","MS","D1","Jackson State"],
  ["Jacksonville State University","AL","D1","Jax State"],
  ["Jacksonville University","FL","D1","Jacksonville"],
  ["James Madison University","VA","D1","James Madison"],
  ["Jarvis Christian University","TX","NAIA"],
  ["Jefferson College","MO","JUCO"],
  ["Jessup University","CA","D2"],
  ["John Brown University","AR","NAIA"],
  ["John Carroll University","OH","D3"],
  ["John Jay College of Criminal Justice","NY","D3"],
  ["Johns Hopkins University","MD","D3"],
  ["Johnson & Wales University","RI","D3"],
  ["Johnson & Wales University Charlotte","NC","D3"],
  ["Johnson C. Smith University","NC","D2"],
  ["Johnson County Community College","KS","JUCO"],
  ["Johnson University","TN","NAIA"],
  ["Judson University","IL","NAIA"],
  ["Juniata College","PA","D3"],
  ["Kalamazoo College","MI","D3"],
  ["Kansas City Kansas Community College","KS","JUCO"],
  ["Kansas State University","KS","D1","Kansas State"],
  ["Kansas Wesleyan University","KS","NAIA"],
  ["Kean University","NJ","D3"],
  ["Keene State College","NH","D3"],
  ["Keiser University","FL","NAIA"],
  ["Kennesaw State University","GA","D1","Kennesaw State"],
  ["Kent State University","OH","D1","Kent State"],
  ["Kentucky Christian University","KY","NAIA"],
  ["Kentucky State University","KY","D2"],
  ["Kentucky Wesleyan College","KY","D2"],
  ["Kenyon College","OH","D3"],
  ["Keuka College","NY","D3"],
  ["Keystone College","PA","D3"],
  ["King University","TN","D2"],
  ["King's College","PA","D3"],
  ["Kirkwood Community College","IA","JUCO"],
  ["Knox College","IL","D3"],
  ["Kutztown University","PA","D2"],
  ["La Roche University","PA","D3"],
  ["La Salle University","PA","D1","La Salle"],
  ["La Sierra University","CA","NAIA"],
  ["LaGrange College","GA","D3"],
  ["Labette Community College","KS","JUCO"],
  ["Lackawanna College","PA","D2"],
  ["Lafayette College","PA","D1","Lafayette"],
  ["Lake Erie College","OH","D2"],
  ["Lake Forest College","IL","D3"],
  ["Lake Superior State University","MI","D2"],
  ["Lakeland University","WI","D3"],
  ["Lamar University","TX","D1","Lamar"],
  ["Lancaster Bible College","PA","D3"],
  ["Lander University","SC","D2"],
  ["Lane College","TN","D2"],
  ["Langston University","OK","NAIA"],
  ["Lasell University","MA","D3"],
  ["Lawrence Technological University(Lawrence Tech)","MI","NAIA"],
  ["Lawrence University","WI","D3"],
  ["Le Moyne College","NY","D1","Le Moyne"],
  ["LeMoyne–Owen College","TN","D2"],
  ["LeTourneau University","TX","D3"],
  ["Lebanon Valley College","PA","D3"],
  ["Lee University","TN","D2"],
  ["Lees–McRae College","NC","D2"],
  ["Lehigh University","PA","D1","Lehigh"],
  ["Lehman College","NY","D3"],
  ["Leland Stanford Junior University","CA","D1","Stanford"],
  ["Lenoir–Rhyne University","NC","D2"],
  ["Lesley University","MA","D3"],
  ["Lewis & Clark College","OR","D3"],
  ["Lewis University","IL","D2"],
  ["Lewis–Clark State College","ID","NAIA"],
  ["Liberty University","VA","D1","Liberty"],
  ["Life Pacific University","CA","NAIA"],
  ["Life University","GA","NAIA"],
  ["Lincoln Memorial University","TN","D2"],
  ["Lincoln University (MO)","MO","D2"],
  ["Lincoln University (PA)","PA","D2"],
  ["Lindenwood University","MO","D1","Lindenwood"],
  ["Lindsey Wilson University","KY","NAIA"],
  ["Linfield University","OR","D3"],
  ["Lipscomb University","TN","D1","Lipscomb"],
  ["Livingstone College","NC","D2"],
  ["Long Island University","NY","D1","LIU"],
  ["Longwood University","VA","D1","Longwood"],
  ["Loras College","IA","D3"],
  ["Louisiana Christian University","LA","NAIA"],
  ["Louisiana State University New Orleans","LA","D1","LSU New Orleans"],
  ["Louisiana State University and Agricultural and Mechanical College","LA","D1","LSU"],
  ["Louisiana State University at Alexandria (LSU Alexandria)","LA","NAIA"],
  ["Louisiana State University in Shreveport (LSU Shreveport)","LA","NAIA"],
  ["Louisiana Tech University","LA","D1","Louisiana Tech"],
  ["Loyola Marymount University","CA","D1","Loyola Marymount"],
  ["Loyola University Chicago","IL","D1","Loyola Chicago"],
  ["Loyola University Maryland","MD","D1","Loyola"],
  ["Loyola University New Orleans","LA","D2"],
  ["Lubbock Christian University","TX","D2"],
  ["Luther College","IA","D3"],
  ["Lycoming College","PA","D3"],
  ["Lynn University","FL","D2"],
  ["Lyon College","AR","D3"],
  ["Macalester College","MN","D3"],
  ["Madonna University","MI","NAIA"],
  ["Maine Maritime Academy","ME","D3"],
  ["Malone University","OH","D2"],
  ["Manchester University","IN","D3"],
  ["Manhattan University","NY","D1","Manhattan"],
  ["Manhattanville University","NY","D3"],
  ["Maranatha Baptist University","WI","D3"],
  ["Marian University","WI","D3"],
  ["Marietta College","OH","D3"],
  ["Marist University","NY","D1","Marist"],
  ["Marquette University","WI","D1","Marquette"],
  ["Mars Hill University","NC","D2"],
  ["Marshall University","WV","D1","Marshall"],
  ["Martin Luther College","MN","D3"],
  ["Mary Baldwin University","VA","D3"],
  ["Marymount University","VA","D3"],
  ["Maryville College","TN","D3"],
  ["Maryville University","MO","D2"],
  ["Marywood University","PA","D3"],
  ["Massachusetts College of Liberal Arts","MA","D3"],
  ["Massachusetts Institute of Technology","MA","D3"],
  ["Massachusetts Maritime Academy","MA","D3"],
  ["Mayville State University","ND","NAIA"],
  ["McDaniel College","MD","D3"],
  ["McKendree University","IL","D2"],
  ["McMurry University","TX","D3"],
  ["McNeese State University","LA","D1","McNeese"],
  ["McPherson College","KS","NAIA"],
  ["Medgar Evers College","NY","D3"],
  ["Menlo College","CA","D2"],
  ["Mercer University","GA","D1","Mercer"],
  ["Mercy University","NY","D2"],
  ["Mercyhurst University","PA","D2"],
  ["Meredith College","NC","D3"],
  ["Merrimack College","MA","D1","Merrimack"],
  ["Messiah University","PA","D3"],
  ["Methodist University","NC","D3"],
  ["Metropolitan Community College","MO","JUCO"],
  ["Metropolitan State University of Denver","CO","D2"],
  ["Miami University","OH","D1","Miami (Ohio)"],
  ["Michigan State University","MI","D1","Michigan State"],
  ["Michigan Technological University","MI","D2"],
  ["Mid-America Christian University","OK","NAIA"],
  ["MidAmerica Nazarene University","KS","NAIA"],
  ["Middle Georgia State University","GA","D2"],
  ["Middle Tennessee State University","TN","D1","Middle Tennessee"],
  ["Middlebury College","VT","D3"],
  ["Midland University","NE","NAIA"],
  ["Midway University","KY","NAIA"],
  ["Midwestern State University","TX","D2"],
  ["Miles College","AL","D2"],
  ["Millersville University","PA","D2"],
  ["Milligan University","TN","NAIA"],
  ["Millikin University","IL","D3"],
  ["Millsaps College","MS","D3"],
  ["Milwaukee School of Engineering","WI","D3"],
  ["Mineral Area College","MO","JUCO"],
  ["Minnesota State University Moorhead","MN","D2"],
  ["Minnesota State University, Mankato","MN","D2"],
  ["Minot State University","ND","D2"],
  ["Misericordia University","PA","D3"],
  ["Mission University","MO","NAIA"],
  ["Mississippi Christian University","MS","D2"],
  ["Mississippi State University","MS","D1","Mississippi State"],
  ["Mississippi University for Women","MS","D3"],
  ["Mississippi Valley State University","MS","D1","Mississippi Valley State"],
  ["Missouri Baptist University","MO","NAIA"],
  ["Missouri Southern State University","MO","D2"],
  ["Missouri State University","MO","D1","Missouri State"],
  ["Missouri University of Science and Technology","MO","D2"],
  ["Missouri Valley College","MO","NAIA"],
  ["Missouri Western State University","MO","D2"],
  ["Mitchell College","CT","D3"],
  ["Moberly Area Community College","MO","JUCO"],
  ["Molloy University","NY","D2"],
  ["Monmouth College","IL","D3"],
  ["Monmouth University","NJ","D1","Monmouth"],
  ["Monroe University","NY","D2"],
  ["Montana State University","MT","D1","Montana State"],
  ["Montana State University Billings","MT","D2"],
  ["Montana State University–Northern","MT","NAIA"],
  ["Montana Technological University(Montana Tech)","MT","NAIA"],
  ["Montclair State University","NJ","D3"],
  ["Montreat College","NC","NAIA"],
  ["Moravian University","PA","D3"],
  ["Morehead State University","KY","D1","Morehead State"],
  ["Morehouse College","GA","D2"],
  ["Morgan State University","MD","D1","Morgan State"],
  ["Morningside University","IA","NAIA"],
  ["Morris College","SC","NAIA"],
  ["Mount Aloysius College","PA","D3"],
  ["Mount Holyoke College","MA","D3"],
  ["Mount Marty University","SD","NAIA"],
  ["Mount Mary University","WI","NAIA"],
  ["Mount Mercy University","IA","NAIA"],
  ["Mount Saint Mary College","NY","D3"],
  ["Mount Saint Mary's University","MD","D1","Mount St. Mary's"],
  ["Mount St. Joseph University","OH","D3"],
  ["Mount Vernon Nazarene University","OH","NAIA"],
  ["Muhlenberg College","PA","D3"],
  ["Murray State University","KY","D1","Murray State"],
  ["Muskingum University","OH","D3"],
  ["Nazareth University","NY","D3"],
  ["Nebraska Wesleyan University","NE","D3"],
  ["Nelson University","TX","NAIA"],
  ["Neosho County Community College","KS","JUCO"],
  ["Neumann University","PA","D3"],
  ["Nevada State University*","NV","NAIA"],
  ["New College of Florida","FL","NAIA"],
  ["New England College","NH","D3"],
  ["New Jersey Institute of Technology","NJ","D1","NJIT"],
  ["New Mexico Highlands University","NM","D2"],
  ["New Mexico State University","NM","D1","New Mexico State"],
  ["New York University","NY","D3"],
  ["Newberry College","SC","D2"],
  ["Newman University","KS","D2"],
  ["Niagara University","NY","D1","Niagara"],
  ["Nicholls State University","LA","D1","Nicholls"],
  ["Nichols College","MA","D3"],
  ["Norfolk State University","VA","D1","Norfolk State"],
  ["North American University","TX","NAIA"],
  ["North Carolina Agricultural and Technical State University","NC","D1","North Carolina A&T"],
  ["North Carolina Central University","NC","D1","North Carolina Central"],
  ["North Carolina State University","NC","D1","NC State"],
  ["North Carolina Wesleyan University","NC","D3"],
  ["North Central College","IL","D3"],
  ["North Central Missouri College","MO","JUCO"],
  ["North Central University","MN","D3"],
  ["North Dakota State University of Agriculture and Applied Sciences","ND","D1","North Dakota State"],
  ["North Greenville University","SC","D2"],
  ["North Park University","IL","D3"],
  ["Northeast Community College","NE","JUCO"],
  ["Northeastern Oklahoma A&M College","OK","JUCO"],
  ["Northeastern State University","OK","D2"],
  ["Northeastern University","MA","D1","Northeastern"],
  ["Northern Arizona University","AZ","D1","Northern Arizona"],
  ["Northern Illinois University","IL","D1","Northern Illinois"],
  ["Northern Kentucky University","KY","D1","Northern Kentucky"],
  ["Northern Michigan University","MI","D2"],
  ["Northern New Mexico College","NM","NAIA"],
  ["Northern State University","SD","D2"],
  ["Northwest Missouri State University","MO","D2"],
  ["Northwest Nazarene University","ID","D2"],
  ["Northwest University","WA","NAIA"],
  ["Northwestern College","IA","NAIA"],
  ["Northwestern Oklahoma State University","OK","D2"],
  ["Northwestern State University of Louisiana","LA","D1","Northwestern State"],
  ["Northwestern University","IL","D1","Northwestern"],
  ["Northwood University","MI","D2"],
  ["Norwich University","VT","D3"],
  ["Notre Dame of Maryland University","MD","D3"],
  ["Nova Southeastern University","FL","D2"],
  ["Oakland University","MI","D1","Oakland"],
  ["Oakwood University","AL","NAIA"],
  ["Oberlin College","OH","D3"],
  ["Occidental College","CA","D3"],
  ["Oglethorpe University","GA","D3"],
  ["Ohio Dominican University","OH","D2"],
  ["Ohio Northern University","OH","D3"],
  ["Ohio Wesleyan University","DE","D3"],
  ["Oklahoma Baptist University","OK","D2"],
  ["Oklahoma Christian University","OK","D2"],
  ["Oklahoma City University","OK","NAIA"],
  ["Oklahoma Panhandle State University","OK","NAIA"],
  ["Oklahoma State University–Stillwater","OK","D1","Oklahoma State"],
  ["Oklahoma Wesleyan University","OK","NAIA"],
  ["Old Dominion University","VA","D1","Old Dominion"],
  ["Olivet Nazarene University","IL","NAIA"],
  ["Oral Roberts University","OK","D1","Oral Roberts"],
  ["Oregon Institute of Technology(Oregon Tech)","OR","NAIA"],
  ["Oregon State University","OR","D1","Oregon State"],
  ["Ottawa University","KS","NAIA"],
  ["Ottawa University Arizona (OUAZ)","AZ","NAIA"],
  ["Otterbein University","OH","D3"],
  ["Ouachita Baptist University","AR","D2"],
  ["Our Lady of the Lake University","TX","NAIA"],
  ["Pace University","NY","D2"],
  ["Pacific Lutheran University","WA","D3"],
  ["Pacific Union College","CA","NAIA"],
  ["Pacific University","OR","D3"],
  ["Palm Beach Atlantic University","FL","D2"],
  ["Park University","MO","NAIA"],
  ["Park University Gilbert","AZ","NAIA"],
  ["Paul Quinn College","TX","NAIA"],
  ["PennWest California","CA","D2"],
  ["PennWest Clarion","PA","D2"],
  ["PennWest Edinboro","PA","D2"],
  ["Pennsylvania College of Technology","PA","D3"],
  ["Pennsylvania State University, Abington","PA","D3"],
  ["Pennsylvania State University, Altoona","PA","D3"],
  ["Pennsylvania State University, Behrend","PA","D3"],
  ["Pennsylvania State University, Berks College","PA","D3"],
  ["Pennsylvania State University, Brandywine","PA","D3"],
  ["Pennsylvania State University, Harrisburg","PA","D3"],
  ["Pepperdine University","CA","D1","Pepperdine"],
  ["Peru State College","NE","NAIA"],
  ["Pfeiffer University","NC","D3"],
  ["Philander Smith University","AR","NAIA"],
  ["Piedmont University","GA","D3"],
  ["Pittsburg State University","KS","D2"],
  ["Plymouth State University","NH","D3"],
  ["Point Loma Nazarene University","CA","D2"],
  ["Point Park University","PA","D2"],
  ["Point University","GA","NAIA"],
  ["Pomona College and Pitzer College","CA","D3"],
  ["Portland State University","OR","D1","Portland State"],
  ["Post University","CT","D2"],
  ["Prairie View A&M University","TX","D1","Prairie View A&M"],
  ["Pratt Community College","KS","JUCO"],
  ["Pratt Institute","NY","D3"],
  ["Presbyterian College","SC","D1","Presbyterian"],
  ["Princeton University","NJ","D1","Princeton"],
  ["Principia College","IL","D3"],
  ["Providence College","RI","D1","Providence"],
  ["Purdue University","IN","D1","Purdue"],
  ["Purdue University Fort Wayne","IN","D1","Purdue Fort Wayne"],
  ["Purdue University Northwest","IN","D2"],
  ["Queens College","NY","D2"],
  ["Queens University of Charlotte","NC","D1","Queens (NC)"],
  ["Quincy University","IL","D2"],
  ["Quinnipiac University","CT","D1","Quinnipiac"],
  ["Radford University","VA","D1","Radford"],
  ["Ramapo College","NJ","D3"],
  ["Randolph College","VA","D3"],
  ["Randolph–Macon College","VA","D3"],
  ["Redlands Community College","OK","JUCO"],
  ["Regent University","VA","D3"],
  ["Regis College","MA","D3"],
  ["Regis University","CO","D2"],
  ["Reinhardt University","GA","NAIA"],
  ["Rensselaer Polytechnic Institute","NY","D3"],
  ["Rhode Island College","RI","D3"],
  ["Rhodes College","TN","D3"],
  ["Rider University","NJ","D1","Rider"],
  ["Ripon College","WI","D3"],
  ["Rivier University","NH","D3"],
  ["Roanoke College","VA","D3"],
  ["Robert Morris University","PA","D1","Robert Morris"],
  ["Roberts Wesleyan University","NY","D2"],
  ["Rochester Christian University","MI","NAIA"],
  ["Rochester Institute of Technology","NY","D3"],
  ["Rockford University","IL","D3"],
  ["Rockhurst University","MO","D2"],
  ["Rocky Mountain College","MT","NAIA"],
  ["Roger Williams University","RI","D3"],
  ["Rogers State University","OK","D2"],
  ["Rollins College","FL","D2"],
  ["Roosevelt University","IL","D2"],
  ["Rose-Hulman Institute of Technology","IN","D3"],
  ["Rowan University","NJ","D3"],
  ["Russell Sage College","NY","D3"],
  ["Rust College","MS","NAIA"],
  ["Rutgers University–Camden","NJ","D3"],
  ["Rutgers University–New Brunswick","NJ","D1","Rutgers"],
  ["Rutgers University–Newark","NJ","D3"],
  ["Sacred Heart University","CT","D1","Sacred Heart"],
  ["Saginaw Valley State University","MI","D2"],
  ["Saint Anselm College","NH","D2"],
  ["Saint Bonaventure University","NY","D1","St. Bonaventure"],
  ["Saint Elizabeth University","NJ","D3"],
  ["Saint Francis University","PA","D3"],
  ["Saint John's University","NY","D1","St. John's"],
  ["Saint Joseph's College of Maine","ME","D3"],
  ["Saint Joseph's University","PA","D1","Saint Joseph's"],
  ["Saint Leo University","FL","D2"],
  ["Saint Louis University","MO","D1","Saint Louis"],
  ["Saint Martin's University","WA","D2"],
  ["Saint Mary's College","IN","D3"],
  ["Saint Mary's College of California","CA","D1","Saint Mary's"],
  ["Saint Mary's University of Minnesota","MN","D3"],
  ["Saint Mary-of-the-Woods College (SMWC)","IN","NAIA"],
  ["Saint Michael's College","VT","D2"],
  ["Saint Peter's University","NJ","D1","Saint Peter's"],
  ["Saint Vincent College","PA","D3"],
  ["Saint Xavier University","IL","NAIA"],
  ["Salem College","NC","D3"],
  ["Salem State University","MA","D3"],
  ["Salem University","WV","D2"],
  ["Salisbury University","MD","D3"],
  ["Salve Regina University","RI","D3"],
  ["Sam Houston State University","TX","D1","Sam Houston"],
  ["Samford University","AL","D1","Samford"],
  ["San Diego State University","CA","D1","San Diego State"],
  ["San Francisco State University","CA","D2"],
  ["San Jose State University","CA","D1","San Jose State"],
  ["Santa Clara University","CA","D1","Santa Clara"],
  ["Sarah Lawrence College","NY","D3"],
  ["Savannah College of Art and Design*","GA","NAIA"],
  ["Savannah State University","GA","D2"],
  ["Schreiner University","TX","D3"],
  ["Seattle Pacific University","WA","D2"],
  ["Seattle University","WA","D1","Seattle"],
  ["Seminole State College","OK","JUCO"],
  ["Seton Hall University","NJ","D1","Seton Hall"],
  ["Seton Hill University","PA","D2"],
  ["Seward County Community College","KS","JUCO"],
  ["Shaw University","NC","D2"],
  ["Shawnee State University","OH","D2"],
  ["Shenandoah University","VA","D3"],
  ["Shepherd University","WV","D2"],
  ["Shippensburg University","PA","D2"],
  ["Shorter University","GA","D2"],
  ["Siena University","NY","D1","Siena"],
  ["Simmons University","MA","D3"],
  ["Simpson College","IA","D3"],
  ["Simpson University","CA","NAIA"],
  ["Skidmore College","NY","D3"],
  ["Slippery Rock University","PA","D2"],
  ["Smith College","MA","D3"],
  ["Soka University of America*","CA","NAIA"],
  ["South Carolina State University","SC","D1","South Carolina State"],
  ["South Dakota School of Mines and Technology","SD","D2"],
  ["South Dakota State University","SD","D1","South Dakota State"],
  ["Southeast Community College","NE","JUCO"],
  ["Southeast Missouri State University","MO","D1","SEMO"],
  ["Southeastern Community College","IA","JUCO"],
  ["Southeastern Louisiana University","LA","D1","Southeastern Louisiana"],
  ["Southeastern Oklahoma State University","OK","D2"],
  ["Southeastern University","FL","NAIA"],
  ["Southern Arkansas University","AR","D2"],
  ["Southern Connecticut State University","CT","D2"],
  ["Southern Illinois University Carbondale","IL","D1","Southern Illinois"],
  ["Southern Illinois University Edwardsville","IL","D1","SIUE"],
  ["Southern Methodist University","TX","D1","SMU"],
  ["Southern Nazarene University","OK","D2"],
  ["Southern New Hampshire University","NH","D2"],
  ["Southern Oregon University","OR","NAIA"],
  ["Southern University and A&M College","LA","D1","Southern"],
  ["Southern University at New Orleans (SUNO)","LA","NAIA"],
  ["Southern Utah University","UT","D1","Southern Utah"],
  ["Southern Virginia University","VA","D3"],
  ["Southern Wesleyan University","SC","D2"],
  ["Southwest Baptist University","MO","D2"],
  ["Southwest Minnesota State University","MN","D2"],
  ["Southwestern Christian University","OK","NAIA"],
  ["Southwestern College","KS","NAIA"],
  ["Southwestern Oklahoma State University","OK","D2"],
  ["Southwestern University","TX","D3"],
  ["Spalding University","KY","D3"],
  ["Spartanburg Methodist College","SC","NAIA"],
  ["Spring Arbor University","MI","NAIA"],
  ["Spring Hill College","AL","D2"],
  ["Springfield College","MA","D3"],
  ["St. Ambrose University","IA","NAIA"],
  ["St. Catherine University","MN","D3"],
  ["St. Cloud State University","MN","D2"],
  ["St. Edward's University","TX","D2"],
  ["St. John Fisher University","NY","D3"],
  ["St. Joseph's University","NY","D3"],
  ["St. Lawrence University","NY","D3"],
  ["St. Mary's College of Maryland","MD","D3"],
  ["St. Mary's University","TX","D2"],
  ["St. Norbert College","WI","D3"],
  ["St. Olaf College","MN","D3"],
  ["St. Thomas Aquinas College","NY","D2"],
  ["St. Thomas University","FL","NAIA"],
  ["Stanton University","CA","NAIA"],
  ["State Fair Community College","MO","JUCO"],
  ["State University of Iowa","IA","D1","Iowa"],
  ["State University of New York Maritime College","NY","D3"],
  ["State University of New York Polytechnic Institute","NY","D3"],
  ["State University of New York at Albany","NY","D1","Albany"],
  ["State University of New York at Binghamton","NY","D1","Binghamton"],
  ["State University of New York at Brockport","NY","D3"],
  ["State University of New York at Buffalo","NY","D1","Buffalo"],
  ["State University of New York at Canton","NY","D3"],
  ["State University of New York at Cobleskill","NY","D3"],
  ["State University of New York at Cortland","NY","D3"],
  ["State University of New York at Delhi","NY","D3"],
  ["State University of New York at Fredonia","NY","D3"],
  ["State University of New York at Geneseo","NY","D3"],
  ["State University of New York at Morrisville","NY","D3"],
  ["State University of New York at New Paltz","NY","D3"],
  ["State University of New York at Old Westbury","NY","D3"],
  ["State University of New York at Oneonta","NY","D3"],
  ["State University of New York at Oswego","NY","D3"],
  ["State University of New York at Plattsburgh","NY","D3"],
  ["State University of New York at Potsdam","NY","D3"],
  ["State University of New York at Purchase","NY","D3"],
  ["State University of New York at Stony Brook","NY","D1","Stony Brook"],
  ["Stephen F. Austin State University","TX","D1","Stephen F. Austin"],
  ["Stephens College","MO","NAIA"],
  ["Sterling College","KS","NAIA"],
  ["Stetson University","FL","D1","Stetson"],
  ["Stevens Institute of Technology","NJ","D3"],
  ["Stevenson University","MD","D3"],
  ["Stillman College","AL","NAIA"],
  ["Stockton University","NJ","D3"],
  ["Stonehill College","MA","D1","Stonehill"],
  ["Suffolk University","MA","D3"],
  ["Sul Ross State University","TX","D2"],
  ["Susquehanna University","PA","D3"],
  ["Swarthmore College","PA","D3"],
  ["Sweet Briar College","VA","D3"],
  ["Syracuse University","NY","D1","Syracuse"],
  ["Tabor College","KS","NAIA"],
  ["Talladega College","AL","NAIA"],
  ["Tarleton State University","TX","D1","Tarleton State"],
  ["Taylor University","IN","NAIA"],
  ["Temple University","PA","D1","Temple"],
  ["Tennessee State University","TN","D1","Tennessee State"],
  ["Tennessee Technological University","TN","D1","Tennessee Tech"],
  ["Tennessee Wesleyan University","TN","NAIA"],
  ["Texas A&M International University","TX","D2"],
  ["Texas A&M University","TX","D1","Texas A&M"],
  ["Texas A&M University–Corpus Christi","TX","D1","Texas A&M–Corpus Christi"],
  ["Texas A&M University–Kingsville","TX","D2"],
  ["Texas A&M University–San Antonio","TX","NAIA"],
  ["Texas A&M University–Texarkana","TX","D2"],
  ["Texas A&M University–Victoria*","TX","NAIA"],
  ["Texas Christian University","TX","D1","TCU"],
  ["Texas College","TX","NAIA"],
  ["Texas Lutheran University","TX","D3"],
  ["Texas Southern University","TX","D1","Texas Southern"],
  ["Texas State University","TX","D1","Texas State"],
  ["Texas Tech University","TX","D1","Texas Tech"],
  ["Texas Wesleyan University","TX","D2"],
  ["Texas Woman's University","TX","D2"],
  ["The Citadel, The Military College of South Carolina","SC","D1","The Citadel"],
  ["The College of New Jersey","NJ","D3"],
  ["The College of St. Scholastica","MN","D3"],
  ["The College of William and Mary in Virginia","VA","D1","William & Mary"],
  ["The Evergreen State College","WA","NAIA"],
  ["The George Washington University","WA","D1","George Washington"],
  ["The Master's University","CA","NAIA"],
  ["The Ohio State University","OH","D1","Ohio State"],
  ["The Ohio University","OH","D1","Ohio"],
  ["The Pennsylvania State University","PA","D1","Penn State"],
  ["The University of Akron","OH","D1","Akron"],
  ["The University of Alabama","AL","D1","Alabama"],
  ["The University of Mississippi","MS","D1","Ole Miss"],
  ["The University of New Mexico","NM","D1","New Mexico"],
  ["The University of Tennessee at Chattanooga","TN","D1","Chattanooga"],
  ["The University of Tennessee at Martin","TN","D1","UT Martin"],
  ["The University of Tennessee, Knoxville","TN","D1","Tennessee"],
  ["The University of Texas Rio Grande Valley","TX","D1","UTRGV"],
  ["The University of Texas at Arlington","TX","D1","UT Arlington"],
  ["The University of Texas at Austin","TX","D1","Texas"],
  ["The University of Texas at El Paso","TX","D1","UTEP"],
  ["The University of Texas at San Antonio","TX","D1","UTSA"],
  ["The University of Tulsa","OK","D1","Tulsa"],
  ["The University of Vermont and State Agricultural College","VT","D1","Vermont"],
  ["Thiel College","PA","D3"],
  ["Thomas College","ME","D3"],
  ["Thomas Jefferson University","PA","D2"],
  ["Thomas More University","KY","D2"],
  ["Thomas University","GA","NAIA"],
  ["Three Rivers College","MO","JUCO"],
  ["Tiffin University","OH","D2"],
  ["Tougaloo College","MS","NAIA"],
  ["Towson University","MD","D1","Towson"],
  ["Transylvania University","KY","D3"],
  ["Trevecca Nazarene University","TN","D2"],
  ["Trine University","IN","D3"],
  ["Trinity College","CT","D3"],
  ["Trinity University","TX","D3"],
  ["Trinity Washington University","WA","D3"],
  ["Troy University","AL","D1","Troy"],
  ["Truett McConnell University","GA","NAIA"],
  ["Truman State University","MO","D2"],
  ["Tufts University","MA","D3"],
  ["Tulane University of Louisiana","LA","D1","Tulane"],
  ["Tusculum University","TN","D2"],
  ["Tuskegee University","AL","D2"],
  ["Union College","NY","D3"],
  ["Union Commonwealth University","KY","NAIA"],
  ["Union University","TN","D2"],
  ["United States Air Force Academy","CO","D1","Air Force"],
  ["United States Coast Guard Academy","CT","D3"],
  ["United States Merchant Marine Academy","NY","D3"],
  ["United States Military Academy","NY","D1","Army / Army West Point"],
  ["United States Naval Academy","MD","D1","Navy"],
  ["United States Sports University*","AL","NAIA"],
  ["University of Alabama at Birmingham","AL","D1","UAB"],
  ["University of Alabama in Huntsville","AL","D2"],
  ["University of Alaska Anchorage","AK","D2"],
  ["University of Alaska Fairbanks","AK","D2"],
  ["University of Arizona","AZ","D1","Arizona"],
  ["University of Arkansas","AR","D1","Arkansas"],
  ["University of Arkansas at Little Rock","AR","D1","Little Rock"],
  ["University of Arkansas at Monticello","AR","D2"],
  ["University of Arkansas at Pine Bluff","AR","D1","Arkansas–Pine Bluff"],
  ["University of Arkansas–Fort Smith","AR","D2"],
  ["University of Bridgeport","CT","D2"],
  ["University of California, Berkeley","CA","D1","California"],
  ["University of California, Davis","CA","D1","UC Davis"],
  ["University of California, Irvine","CA","D1","UC Irvine"],
  ["University of California, Los Angeles","CA","D1","UCLA"],
  ["University of California, Merced","CA","D2"],
  ["University of California, Riverside","CA","D1","UC Riverside"],
  ["University of California, San Diego","CA","D1","UC San Diego"],
  ["University of California, Santa Barbara","CA","D1","UC Santa Barbara"],
  ["University of California, Santa Cruz","CA","D3"],
  ["University of Central Arkansas","AR","D1","Central Arkansas"],
  ["University of Central Florida","FL","D1","UCF"],
  ["University of Central Missouri","MO","D2"],
  ["University of Central Oklahoma","OK","D2"],
  ["University of Charleston","WV","D2"],
  ["University of Chicago","IL","D3"],
  ["University of Cincinnati","OH","D1","Cincinnati"],
  ["University of Colorado Boulder","CO","D1","Colorado"],
  ["University of Colorado Colorado Springs","CO","D2"],
  ["University of Connecticut","CT","D1","UConn"],
  ["University of Dallas","TX","D3"],
  ["University of Dayton","OH","D1","Dayton"],
  ["University of Delaware","DE","D1","Delaware"],
  ["University of Denver","CO","D1","Denver"],
  ["University of Detroit Mercy","MI","D1","Detroit Mercy"],
  ["University of Dubuque","IA","D3"],
  ["University of Evansville","IN","D1","Evansville"],
  ["University of Findlay","OH","D2"],
  ["University of Florida","FL","D1","Florida"],
  ["University of Georgia","GA","D1","Georgia"],
  ["University of Hartford","CT","D3"],
  ["University of Hawai'i at Hilo","HI","D2"],
  ["University of Hawaiʻi at Mānoa","HI","D1","Hawaiʻi"],
  ["University of Houston","TX","D1","Houston"],
  ["University of Idaho","ID","D1","Idaho"],
  ["University of Illinois Chicago","IL","D1","UIC"],
  ["University of Illinois Urbana-Champaign","IL","D1","Illinois"],
  ["University of Illinois at Springfield","IL","D2"],
  ["University of Indianapolis","IN","D2"],
  ["University of Jamestown","ND","D2"],
  ["University of Kansas","KS","D1","Kansas"],
  ["University of Kentucky","KY","D1","Kentucky"],
  ["University of La Verne","CA","D3"],
  ["University of Louisiana at Lafayette","LA","D1","Louisiana"],
  ["University of Louisiana at Monroe","LA","D1","ULM"],
  ["University of Louisville","KY","D1","Louisville"],
  ["University of Lynchburg","VA","D3"],
  ["University of Maine","ME","D1","Maine"],
  ["University of Maine at Augusta","ME","D3"],
  ["University of Maine at Farmington","ME","D3"],
  ["University of Maine at Presque Isle","ME","D3"],
  ["University of Mary","ND","D2"],
  ["University of Mary Hardin–Baylor","TX","D3"],
  ["University of Mary Washington","VA","D3"],
  ["University of Maryland Eastern Shore","MD","D1","Maryland Eastern Shore"],
  ["University of Maryland, Baltimore County","MD","D1","UMBC"],
  ["University of Maryland, College Park","MD","D1","Maryland"],
  ["University of Massachusetts Amherst","MA","D1","UMass / Massachusetts"],
  ["University of Massachusetts Boston","MA","D3"],
  ["University of Massachusetts Dartmouth","MA","D3"],
  ["University of Massachusetts Lowell","MA","D1","UMass Lowell"],
  ["University of Memphis","TN","D1","Memphis"],
  ["University of Miami","FL","D1","Miami (Florida)"],
  ["University of Michigan","MI","D1","Michigan"],
  ["University of Michigan–Dearborn","MI","NAIA"],
  ["University of Minnesota","MN","D1","Minnesota"],
  ["University of Minnesota Crookston","MN","D2"],
  ["University of Minnesota Duluth","MN","D2"],
  ["University of Minnesota Morris","MN","D3"],
  ["University of Missouri–Columbia","MO","D1","Missouri"],
  ["University of Missouri–Kansas City","MO","D1","Kansas City"],
  ["University of Missouri–St. Louis","MO","D2"],
  ["University of Mobile","AL","NAIA"],
  ["University of Montana","MT","D1","Montana"],
  ["University of Montana–Western","MT","NAIA"],
  ["University of Montevallo","AL","D2"],
  ["University of Mount Olive","NC","D2"],
  ["University of Mount Saint Vincent","NY","D3"],
  ["University of Mount Union","OH","D3"],
  ["University of Nebraska Omaha","NE","D1","Omaha"],
  ["University of Nebraska at Kearney","NE","D2"],
  ["University of Nebraska–Lincoln","NE","D1","Nebraska"],
  ["University of Nevada, Las Vegas","NV","D1","UNLV"],
  ["University of Nevada, Reno","NV","D1","Nevada"],
  ["University of New England","ME","D3"],
  ["University of New Hampshire","NH","D1","New Hampshire"],
  ["University of New Haven","CT","D2"],
  ["University of North Alabama","AL","D1","North Alabama"],
  ["University of North Carolina at Asheville","NC","D1","UNC Asheville"],
  ["University of North Carolina at Chapel Hill","NC","D1","North Carolina"],
  ["University of North Carolina at Charlotte","NC","D1","Charlotte"],
  ["University of North Carolina at Greensboro","NC","D1","UNC Greensboro"],
  ["University of North Carolina at Pembroke","NC","D2"],
  ["University of North Carolina at Wilmington","NC","D1","UNCW"],
  ["University of North Dakota","ND","D1","North Dakota"],
  ["University of North Florida","FL","D1","North Florida"],
  ["University of North Georgia","GA","D2"],
  ["University of North Texas","TX","D1","North Texas"],
  ["University of North Texas at Dallas","TX","NAIA"],
  ["University of Northern Colorado","CO","D1","Northern Colorado"],
  ["University of Northern Iowa","IA","D1","Northern Iowa"],
  ["University of Northwestern - St. Paul","MN","D3"],
  ["University of Northwestern Ohio (UNOH)","OH","NAIA"],
  ["University of Notre Dame du Lac","IN","D1","Notre Dame"],
  ["University of Oklahoma","OK","D1","Oklahoma"],
  ["University of Olivet","MI","D3"],
  ["University of Oregon","OR","D1","Oregon"],
  ["University of Pennsylvania","PA","D1","Penn"],
  ["University of Pikeville","KY","NAIA"],
  ["University of Pittsburgh","PA","D1","Pittsburgh"],
  ["University of Pittsburgh at Bradford","PA","D3"],
  ["University of Pittsburgh at Greensburg","PA","D3"],
  ["University of Pittsburgh at Johnstown","PA","D2"],
  ["University of Portland","OR","D1","Portland"],
  ["University of Providence","MT","NAIA"],
  ["University of Puerto Rico at Bayamón","PR","D2"],
  ["University of Puerto Rico at Mayagüez","PR","D2"],
  ["University of Puerto Rico at Río Piedras","PR","D2"],
  ["University of Puget Sound","WA","D3"],
  ["University of Redlands","CA","D3"],
  ["University of Rhode Island","RI","D1","Rhode Island"],
  ["University of Richmond","VA","D1","Richmond"],
  ["University of Rio Grande","OH","NAIA"],
  ["University of Rochester","NY","D3"],
  ["University of Saint Francis","IN","NAIA"],
  ["University of Saint Joseph","CT","D3"],
  ["University of Saint Mary","KS","NAIA"],
  ["University of Saint Thomas","MN","D1","St. Thomas"],
  ["University of San Diego","CA","D1","San Diego"],
  ["University of San Francisco","CA","D1","San Francisco"],
  ["University of Science and Arts of Oklahoma","OK","NAIA"],
  ["University of Scranton","PA","D3"],
  ["University of Sioux Falls","SD","D2"],
  ["University of South Alabama","AL","D1","South Alabama"],
  ["University of South Carolina","SC","D1","South Carolina"],
  ["University of South Carolina Aiken","SC","D2"],
  ["University of South Carolina Beaufort","SC","D2"],
  ["University of South Carolina Upstate","SC","D1","USC Upstate"],
  ["University of South Dakota","SD","D1","South Dakota"],
  ["University of South Florida","FL","D1","South Florida"],
  ["University of Southern California","CA","D1","USC"],
  ["University of Southern Indiana","IN","D1","Southern Indiana"],
  ["University of Southern Maine","ME","D3"],
  ["University of Southern Mississippi","MS","D1","Southern Miss"],
  ["University of St. Francis","IL","NAIA"],
  ["University of St. Thomas (Texas)","TX","D3"],
  ["University of Tampa","FL","D2"],
  ["University of Tennessee Southern (UT Southern)","TN","NAIA"],
  ["University of Texas Permian Basin","TX","D2"],
  ["University of Texas at Dallas","TX","D2"],
  ["University of Texas at Tyler","TX","D2"],
  ["University of Toledo","OH","D1","Toledo"],
  ["University of Utah","UT","D1","Utah"],
  ["University of Virginia","VA","D1","Virginia"],
  ["University of Virginia's College at Wise","VA","D2"],
  ["University of Washington","WA","D1","Washington"],
  ["University of West Alabama","AL","D2"],
  ["University of West Florida","FL","D2"],
  ["University of West Georgia","GA","D2"],
  ["University of Wisconsin–Eau Claire","WI","D3"],
  ["University of Wisconsin–Green Bay","WI","D1","Green Bay"],
  ["University of Wisconsin–La Crosse","WI","D3"],
  ["University of Wisconsin–Madison","WI","D1","Wisconsin"],
  ["University of Wisconsin–Milwaukee","WI","D1","Milwaukee"],
  ["University of Wisconsin–Oshkosh","WI","D3"],
  ["University of Wisconsin–Parkside","WI","D2"],
  ["University of Wisconsin–Platteville","WI","D3"],
  ["University of Wisconsin–River Falls","WI","D3"],
  ["University of Wisconsin–Stevens Point","WI","D3"],
  ["University of Wisconsin–Stout","WI","D3"],
  ["University of Wisconsin–Superior","WI","D3"],
  ["University of Wisconsin–Whitewater","WI","D3"],
  ["University of Wyoming","WY","D1","Wyoming"],
  ["University of the Cumberlands","KY","NAIA"],
  ["University of the District of Columbia","WA","D2"],
  ["University of the Incarnate Word","TX","D1","Incarnate Word"],
  ["University of the Ozarks","AR","D3"],
  ["University of the Pacific","CA","D1","Pacific"],
  ["University of the South","TN","D3"],
  ["University of the Southwest","NM","NAIA"],
  ["Upper Iowa University","IA","D2"],
  ["Ursinus College","PA","D3"],
  ["Ursuline College","OH","D2"],
  ["Utah State University","UT","D1","Utah State"],
  ["Utah Tech University","UT","D1","Utah Tech"],
  ["Utah Valley University","UT","D1","Utah Valley"],
  ["Utica University","NY","D3"],
  ["Valdosta State University","GA","D2"],
  ["Valley City State University","ND","NAIA"],
  ["Valparaiso University","IN","D1","Valparaiso"],
  ["Vanderbilt University","TN","D1","Vanderbilt"],
  ["Vanguard University","CA","D2"],
  ["Vassar College","NY","D3"],
  ["Vermont State University–Castleton","VT","D3"],
  ["Vermont State University–Johnson","VT","D3"],
  ["Vermont State University–Lyndon","VT","D3"],
  ["Villanova University","PA","D1","Villanova"],
  ["Virginia Commonwealth University","VA","D1","VCU"],
  ["Virginia Military Institute","VA","D1","VMI"],
  ["Virginia Polytechnic Institute and State University","VA","D1","Virginia Tech"],
  ["Virginia State University","VA","D2"],
  ["Virginia Union University","VA","D2"],
  ["Viterbo University","WI","NAIA"],
  ["Voorhees University","SC","NAIA"],
  ["Wabash College","IN","D3"],
  ["Wagner College","NY","D1","Wagner"],
  ["Wake Forest University","NC","D1","Wake Forest"],
  ["Waldorf University","IA","NAIA"],
  ["Walla Walla University","WA","NAIA"],
  ["Walsh University","OH","D2"],
  ["Warner Pacific University","OR","NAIA"],
  ["Warner University","FL","NAIA"],
  ["Warren Wilson College","NC","D3"],
  ["Wartburg College","IA","D3"],
  ["Washburn University","KS","D2"],
  ["Washington & Jefferson College","WA","D3"],
  ["Washington Adventist University","MD","NAIA"],
  ["Washington College","MD","D3"],
  ["Washington State University","WA","D1","Washington State"],
  ["Washington University in St. Louis","MO","D3"],
  ["Washington and Lee University","VA","D3"],
  ["Wayland Baptist University","TX","NAIA"],
  ["Wayne State College","NE","D2"],
  ["Wayne State University","MI","D2"],
  ["Waynesburg University","PA","D3"],
  ["Webber International University","FL","NAIA"],
  ["Weber State University","UT","D1","Weber State"],
  ["Webster University","MO","D3"],
  ["Wellesley College","MA","D3"],
  ["Wentworth Institute of Technology","MA","D3"],
  ["Wesleyan College","GA","NAIA"],
  ["Wesleyan University","CT","D3"],
  ["West Chester University","PA","D2"],
  ["West Liberty University","WV","D2"],
  ["West Texas A&M University","TX","D2"],
  ["West Virginia State University","WV","D2"],
  ["West Virginia University","WV","D1","West Virginia"],
  ["West Virginia University Institute of Technology (WVU Tech)","WV","NAIA"],
  ["West Virginia Wesleyan College","WV","D2"],
  ["Westcliff University","CA","NAIA"],
  ["Western Carolina University","NC","D1","Western Carolina"],
  ["Western Colorado University","CO","D2"],
  ["Western Connecticut State University","CT","D3"],
  ["Western Illinois University","IL","D1","Western Illinois"],
  ["Western Kentucky University","KY","D1","Western Kentucky"],
  ["Western Michigan University","MI","D1","Western Michigan"],
  ["Western Nebraska Community College","NE","JUCO"],
  ["Western New England University","MA","D3"],
  ["Western New Mexico University","NM","D2"],
  ["Western Oregon University","OR","D2"],
  ["Western Washington University","WA","D2"],
  ["Westfield State University","MA","D3"],
  ["Westminster College","MO","D3"],
  ["Westminster University","UT","D2"],
  ["Westmont College","CA","D2"],
  ["Wheaton College","IL","D3"],
  ["Wheeling University","WV","D2"],
  ["Whitman College","WA","D3"],
  ["Whittier College","CA","D3"],
  ["Whitworth University","WA","D3"],
  ["Wichita State University","KS","D1","Wichita State"],
  ["Widener University","PA","D3"],
  ["Wilberforce University","OH","NAIA"],
  ["Wiley University","TX","NAIA"],
  ["Wilkes University","PA","D3"],
  ["Willamette University","OR","D3"],
  ["William Carey University","MS","NAIA"],
  ["William Jewell College","MO","D2"],
  ["William Marsh Rice University","TX","D1","Rice"],
  ["William Paterson University","NJ","D3"],
  ["William Peace University","NC","D3"],
  ["William Penn University","IA","NAIA"],
  ["William Smith College","NY","D3"],
  ["William Woods University","MO","NAIA"],
  ["Williams Baptist University","AR","NAIA"],
  ["Williams College","MA","D3"],
  ["Wilmington College","OH","D3"],
  ["Wilmington University","DE","D2"],
  ["Wilson College","PA","D3"],
  ["Wingate University","NC","D2"],
  ["Winona State University","MN","D2"],
  ["Winston-Salem State University","NC","D2"],
  ["Winthrop University","SC","D1","Winthrop"],
  ["Wisconsin Lutheran College","WI","D3"],
  ["Wittenberg University","OH","D3"],
  ["Wofford College","SC","D1","Wofford"],
  ["Worcester Polytechnic Institute","MA","D3"],
  ["Worcester State University","MA","D3"],
  ["Wright State University","OH","D1","Wright State"],
  ["Xavier University","OH","D1","Xavier"],
  ["Xavier University of Louisiana","LA","NAIA"],
  ["Yale University","CT","D1","Yale"],
  ["Yeshiva University","NY","D3"],
  ["York College of Pennsylvania","PA","D3"],
  ["York College, City University of New York","NY","D3"],
  ["York University","NE","NAIA"],
  ["Young Harris College","GA","D2"],
  ["Youngstown State University","OH","D1","Youngstown State"],
];
