// AUTO-GENERATED: official athletics brand logo IDs (ESPN CDN, 500px transparent PNG).
// Maps institution name -> team logo id.
export const COLLEGE_LOGO_IDS: Record<string, string> = {
"Abilene Christian University": "2000",
"Alabama Agricultural and Mechanical University": "2010",
"Alabama State University": "2011",
"Alcorn State University": "2016",
"American University": "44",
"Arizona State University": "9",
"Arkansas State University": "2032",
"Auburn University": "2",
"Austin Peay State University": "2046",
"Ball State University": "2050",
"Baylor University": "239",
"Bellarmine University": "91",
"Belmont University": "2057",
"Bethune\u2013Cookman University": "2065",
"Boise State University": "68",
"Boston College": "103",
"Boston University": "103",
"Bowling Green State University": "189",
"Bradley University": "71",
"Brigham Young University": "252",
"Brown University": "225",
"Bryant University": "2803",
"Bucknell University": "2083",
"Butler University": "2086",
"California Baptist University": "2856",
"California Polytechnic State University": "13",
"California State University, Fresno": "278",
"California State University, Fullerton": "2239",
"California State University, Long Beach": "299",
"California State University, Sacramento": "16",
"Campbell University": "2097",
"Canisius University": "2099",
"Central Connecticut State University": "2115",
"Central Michigan University": "2117",
"Charleston Southern University": "2127",
"Chicago State University": "2130",
"Clemson University": "228",
"Cleveland State University": "325",
"Coastal Carolina University": "324",
"Colgate University": "2142",
"College of Charleston": "232",
"College of Idaho": "70",
"College of the Holy Cross": "107",
"Colorado College": "38",
"Colorado State University": "36",
"Columbia University in the City of New York": "171",
"Coppin State University": "2154",
"Cornell College": "172",
"Cornell University": "172",
"Creighton University": "156",
"Dartmouth College": "159",
"Davidson College": "2166",
"DePaul University": "305",
"Delaware State University": "2169",
"Drake University": "2181",
"Drexel University": "2182",
"Duke University": "150",
"Duquesne University of the Holy Spirit": "2184",
"East Carolina University": "151",
"East Tennessee State University": "2193",
"East Texas A&M University": "2837",
"Eastern Illinois University": "2197",
"Eastern Kentucky University": "2198",
"Eastern Michigan University": "2199",
"Eastern Washington University": "331",
"Elon University": "2210",
"Fairfield University": "2217",
"Fairleigh Dickinson University": "161",
"Florida Agricultural and Mechanical University": "50",
"Florida Atlantic University": "2226",
"Florida College": "57",
"Florida Gulf Coast University": "526",
"Florida International University": "2229",
"Florida State University": "52",
"Fordham University": "2230",
"Furman University": "231",
"Gardner\u2013Webb University": "2241",
"George Mason University": "2244",
"Georgetown College": "46",
"Georgetown University": "46",
"Georgia Institute of Technology": "59",
"Georgia Southern University": "290",
"Georgia State University": "2247",
"Gonzaga University": "2250",
"Grand Canyon University": "2253",
"Hampton University": "2261",
"Harvard University": "108",
"High Point University": "2272",
"Hofstra University": "2275",
"Holy Cross College": "107",
"Houston Christian University": "2277",
"Howard University": "47",
"Idaho State University": "304",
"Illinois College": "356",
"Illinois State University": "2287",
"Indiana State University": "282",
"Indiana University Bloomington": "84",
"Indiana University Indianapolis": "85",
"Iona University": "314",
"Iowa State University of Science and Technology": "66",
"Jackson State University": "2296",
"Jacksonville State University": "55",
"Jacksonville University": "294",
"James Madison University": "256",
"Kansas State University": "2306",
"Kennesaw State University": "338",
"Kent State University": "2309",
"La Salle University": "2325",
"Lafayette College": "322",
"Lamar University": "2320",
"Le Moyne College": "2330",
"Lehigh University": "2329",
"Leland Stanford Junior University": "24",
"Liberty University": "2335",
"Lipscomb University": "288",
"Long Island University": "112358",
"Longwood University": "2344",
"Louisiana State University New Orleans": "2443",
"Louisiana State University and Agricultural and Mechanical College": "99",
"Louisiana Tech University": "2348",
"Loyola Marymount University": "2351",
"Loyola University Chicago": "2350",
"Loyola University Maryland": "2352",
"Manhattan University": "2363",
"Marist University": "2368",
"Marquette University": "269",
"Marshall University": "276",
"McNeese State University": "2377",
"Mercer University": "2382",
"Mercyhurst University": "2385",
"Merrimack College": "2771",
"Miami University": "2390",
"Michigan State University": "127",
"Middle Tennessee State University": "2393",
"Mississippi State University": "344",
"Mississippi Valley State University": "2400",
"Missouri State University": "2623",
"Monmouth College": "2405",
"Monmouth University": "2405",
"Montana State University": "147",
"Morehead State University": "2413",
"Morgan State University": "2415",
"Mount Saint Mary's University": "116",
"Murray State University": "93",
"New Jersey Institute of Technology": "2885",
"New Mexico State University": "166",
"Niagara University": "315",
"Nicholls State University": "2447",
"Norfolk State University": "2450",
"North Carolina Agricultural and Technical State University": "2448",
"North Carolina Central University": "2428",
"North Carolina State University": "152",
"North Dakota State University of Agriculture and Applied Sciences": "2449",
"Northeastern University": "111",
"Northern Arizona University": "2464",
"Northern Illinois University": "2459",
"Northern Kentucky University": "94",
"Northwestern College": "77",
"Northwestern State University of Louisiana": "2466",
"Northwestern University": "77",
"Oakland University": "2473",
"Oklahoma State University\u2013Stillwater": "197",
"Old Dominion University": "295",
"Oral Roberts University": "198",
"Oregon State University": "204",
"Pacific University": "279",
"Pepperdine University": "2492",
"Portland State University": "2502",
"Prairie View A&M University": "2504",
"Presbyterian College": "2506",
"Princeton University": "163",
"Providence College": "2507",
"Purdue University": "2509",
"Purdue University Fort Wayne": "2870",
"Quinnipiac University": "2514",
"Radford University": "2515",
"Rhode Island College": "227",
"Rider University": "2520",
"Robert Morris University": "2523",
"Rutgers University\u2013New Brunswick": "164",
"Sacred Heart University": "2529",
"Saint Bonaventure University": "179",
"Saint John's University": "2599",
"Saint Joseph's University": "2603",
"Saint Louis University": "139",
"Saint Mary's College": "2608",
"Saint Mary's College of California": "2608",
"Saint Peter's University": "2612",
"Sam Houston State University": "2534",
"Samford University": "2535",
"San Diego State University": "21",
"Santa Clara University": "2541",
"Seton Hall University": "2550",
"Siena University": "2561",
"South Carolina State University": "2569",
"South Dakota State University": "2571",
"Southeast Missouri State University": "2546",
"Southern Illinois University Carbondale": "79",
"Southern Illinois University Edwardsville": "2565",
"Southern Methodist University": "2567",
"Southern University and A&M College": "2582",
"Southern Utah University": "253",
"St. Thomas University": "2900",
"State University of Iowa": "2294",
"State University of New York at Binghamton": "2066",
"State University of New York at Buffalo": "2084",
"State University of New York at Stony Brook": "2619",
"Stephen F. Austin State University": "2617",
"Stetson University": "56",
"Stonehill College": "284",
"Syracuse University": "183",
"Tarleton State University": "2627",
"Temple University": "218",
"Tennessee State University": "2634",
"Tennessee Technological University": "2635",
"Texas A&M University": "245",
"Texas A&M University\u2013Corpus Christi": "357",
"Texas Christian University": "2628",
"Texas College": "251",
"Texas Southern University": "2640",
"Texas State University": "326",
"Texas Tech University": "2641",
"The Citadel, The Military College of South Carolina": "2643",
"The College of William and Mary in Virginia": "2729",
"The George Washington University": "45",
"The Ohio State University": "194",
"The Ohio University": "195",
"The Pennsylvania State University": "213",
"The University of Akron": "2006",
"The University of Alabama": "333",
"The University of Mississippi": "145",
"The University of New Mexico": "167",
"The University of Tennessee at Chattanooga": "236",
"The University of Tennessee at Martin": "2630",
"The University of Tennessee, Knoxville": "2633",
"The University of Texas at Arlington": "250",
"The University of Texas at Austin": "251",
"The University of Texas at El Paso": "2638",
"The University of Texas at San Antonio": "2636",
"The University of Tulsa": "202",
"The University of Vermont and State Agricultural College": "261",
"Towson University": "119",
"Troy University": "2653",
"Tulane University of Louisiana": "2655",
"United States Air Force Academy": "2005",
"United States Naval Academy": "2426",
"University of Alabama at Birmingham": "5",
"University of Arizona": "12",
"University of Arkansas": "8",
"University of Arkansas at Little Rock": "2031",
"University of Arkansas at Pine Bluff": "2029",
"University of California, Berkeley": "25",
"University of California, Davis": "302",
"University of California, Irvine": "300",
"University of California, Los Angeles": "26",
"University of California, Riverside": "27",
"University of California, San Diego": "28",
"University of California, Santa Barbara": "2540",
"University of Central Arkansas": "2110",
"University of Central Florida": "2116",
"University of Charleston": "232",
"University of Cincinnati": "2132",
"University of Colorado Boulder": "38",
"University of Connecticut": "41",
"University of Dayton": "2168",
"University of Delaware": "48",
"University of Denver": "2172",
"University of Detroit Mercy": "2174",
"University of Evansville": "339",
"University of Florida": "57",
"University of Georgia": "61",
"University of Hawai\u02bbi at M\u0101noa": "62",
"University of Houston": "248",
"University of Idaho": "70",
"University of Illinois Chicago": "82",
"University of Illinois Urbana-Champaign": "356",
"University of Kansas": "2305",
"University of Kentucky": "96",
"University of Louisiana at Lafayette": "309",
"University of Louisiana at Monroe": "2433",
"University of Louisville": "97",
"University of Maine": "311",
"University of Maryland Eastern Shore": "2379",
"University of Maryland, Baltimore County": "2378",
"University of Maryland, College Park": "120",
"University of Massachusetts Lowell": "2349",
"University of Memphis": "235",
"University of Miami": "2390",
"University of Michigan": "130",
"University of Minnesota": "135",
"University of Missouri\u2013Columbia": "142",
"University of Missouri\u2013Kansas City": "140",
"University of Montana": "149",
"University of Nebraska Omaha": "2437",
"University of Nebraska\u2013Lincoln": "158",
"University of Nevada, Las Vegas": "2439",
"University of Nevada, Reno": "2440",
"University of New Hampshire": "160",
"University of New Haven": "2441",
"University of North Alabama": "2453",
"University of North Carolina at Asheville": "2427",
"University of North Carolina at Chapel Hill": "153",
"University of North Carolina at Charlotte": "2429",
"University of North Carolina at Greensboro": "2430",
"University of North Carolina at Wilmington": "350",
"University of North Dakota": "155",
"University of North Florida": "2454",
"University of North Texas": "249",
"University of Northern Colorado": "2458",
"University of Northern Iowa": "2460",
"University of Notre Dame du Lac": "87",
"University of Oklahoma": "201",
"University of Oregon": "2483",
"University of Pennsylvania": "219",
"University of Pittsburgh": "221",
"University of Portland": "2501",
"University of Providence": "2507",
"University of Rhode Island": "227",
"University of Richmond": "257",
"University of Saint Thomas": "2900",
"University of San Diego": "301",
"University of San Francisco": "2539",
"University of South Alabama": "6",
"University of South Carolina": "2579",
"University of South Carolina Upstate": "2908",
"University of South Dakota": "233",
"University of South Florida": "58",
"University of Southern California": "30",
"University of Southern Mississippi": "2572",
"University of Toledo": "2649",
"University of Utah": "254",
"University of Virginia": "258",
"University of Washington": "264",
"University of West Florida": "2697",
"University of West Georgia": "2698",
"University of Wisconsin\u2013Green Bay": "2739",
"University of Wisconsin\u2013Madison": "275",
"University of Wisconsin\u2013Milwaukee": "270",
"University of Wyoming": "2751",
"University of the Incarnate Word": "2916",
"University of the Pacific": "279",
"Utah State University": "328",
"Utah Tech University": "3101",
"Utah Valley University": "3084",
"Valparaiso University": "2674",
"Vanderbilt University": "238",
"Villanova University": "222",
"Virginia Commonwealth University": "2670",
"Virginia Military Institute": "2678",
"Virginia Polytechnic Institute and State University": "259",
"Wagner College": "2681",
"Wake Forest University": "154",
"Washington College": "264",
"Washington State University": "265",
"Weber State University": "2692",
"West Virginia University": "277",
"Western Carolina University": "2717",
"Western Illinois University": "2710",
"Western Kentucky University": "98",
"Western Michigan University": "2711",
"Wichita State University": "2724",
"William Marsh Rice University": "242",
"Winthrop University": "2737",
"Wofford College": "2747",
"Wright State University": "2750",
"Xavier University": "2752",
"Yale University": "43",
"Youngstown State University": "2754"
};
