// AUTO-GENERATED: college name -> primary web domain (for logo lookup).
export const COLLEGE_DOMAINS: Record<string, string> = {
  "Abilene Christian University": "acu.edu",
  "Abraham Baldwin Agricultural College": "abac.edu",
  "Adelphi University": "adelphi.edu",
  "Adrian College": "adrian.edu",
  "Agnes Scott College": "agnesscott.edu",
  "Alabama State University": "alasu.edu",
  "Albany State University": "asurams.edu",
  "Albion College": "albion.edu",
  "Alcorn State University": "alcorn.edu",
  "Alfred University": "alfred.edu",
  "Allegheny College": "alleg.edu",
  "Allen University": "allenuniversity.edu",
  "Alma College": "alma.edu",
  "Alvernia University": "alvernia.edu",
  "Alverno College": "alverno.edu",
  "American International College": "aic.edu",
  "American University": "american.edu",
  "Amherst College": "amherst.edu",
  "Anderson University": "andersonuniversity.edu",
  "Andrew College": "andrewcollege.edu",
  "Angelo State University": "angelo.edu",
  "Appalachian State University": "appstate.edu",
  "Aquinas College": "aquinas.edu",
  "Arcadia University": "arcadia.edu",
  "Arizona State University": "asu.edu",
  "Arkansas Baptist College": "arkansasbaptist.edu",
  "Arkansas State University": "astate.edu",
  "Arkansas Tech University": "atu.edu",
  "Ashland University": "ashland.edu",
  "Assumption University": "assumption.edu",
  "Auburn University": "auburn.edu",
  "Auburn University at Montgomery": "aum.edu",
  "Augsburg University": "augsburg.edu",
  "Augusta University": "augusta.edu",
  "Augustana College": "augustana.edu",
  "Aurora University": "aurora.edu",
  "Austin College": "austincollege.edu",
  "Austin Peay State University": "apsu.edu",
  "Averett University": "averett.edu",
  "Avila University": "avila.edu",
  "Azusa Pacific University": "apu.edu",
  "Babson College": "babson.edu",
  "Baker University": "bakeru.edu",
  "Baldwin Wallace University": "bw.edu",
  "Ball State University": "bsu.edu",
  "Bard College": "bard.edu",
  "Barry University": "barry.edu",
  "Baruch College": "baruch.cuny.edu",
  "Bates College": "bates.edu",
  "Baylor University": "baylor.edu",
  "Belhaven University": "belhaven.edu",
  "Bellevue University": "bellevue.edu",
  "Belmont University": "belmont.edu",
  "Beloit College": "beloit.edu",
  "Bemidji State University": "bemidjistate.edu",
  "Benedict College": "benedict.edu",
  "Benedictine College": "benedictine.edu",
  "Benedictine University": "benedictine.edu",
  "Bentley University": "bentley.edu",
  "Berea College": "berea.edu",
  "Berry College": "berry.edu",
  "Bethany College": "bethanywv.edu",
  "Bethel College (KS)": "bethelks.edu",
  "Bethel University": "bethel.edu",
  "Bethel University (IN)": "bethel.edu",
  "Bethel University (TN)": "bethel.edu",
  "Bethune\u2013Cookman University": "cookman.edu",
  "Biola University": "biola.edu",
  "Black Hills State University": "bhsu.edu",
  "Bluefield State University": "bluefieldstate.edu",
  "Bluffton University": "bluffton.edu",
  "Boise State University": "boisestate.edu",
  "Boston College": "bc.edu",
  "Boston University": "bu.edu",
  "Bowdoin College": "bowdoin.edu",
  "Bowie State University": "bowiestate.edu",
  "Bowling Green State University": "bgsu.edu",
  "Bradley University": "bradley.edu",
  "Brandeis University": "brandeis.edu",
  "Brenau University": "brenau.edu",
  "Brescia University": "brescia.edu",
  "Briar Cliff University": "briar-cliff.edu",
  "Bridgewater College": "bridgewater.edu",
  "Bridgewater State University": "bridgew.edu",
  "Brigham Young University": "byu.edu",
  "Brooklyn College": "brooklyn.cuny.edu",
  "Brown University": "brown.edu",
  "Bryant University": "bryant.edu",
  "Bryn Mawr College": "brynmawr.edu",
  "Bucknell University": "bucknell.edu",
  "Buena Vista University": "bvu.edu",
  "Butler Community College": "butlercc.edu",
  "Butler University": "butler.edu",
  "Caldwell University": "caldwell.edu",
  "California Baptist University": "calbaptist.edu",
  "California Institute of Technology": "caltech.edu",
  "California Lutheran University": "callutheran.edu",
  "California Polytechnic State University": "cpp.edu",
  "California State University San Marcos": "csusm.edu",
  "California State University, Bakersfield": "csub.edu",
  "California State University, Chico": "csuchico.edu",
  "California State University, Dominguez Hills": "csudh.edu",
  "California State University, East Bay": "csueastbay.edu",
  "California State University, Fresno": "csufresno.edu",
  "California State University, Fullerton": "fullerton.edu",
  "California State University, Long Beach": "csulb.edu",
  "California State University, Los Angeles": "calstatela.edu",
  "California State University, Monterey Bay": "csumb.edu",
  "California State University, Northridge": "csun.edu",
  "California State University, Sacramento": "csus.edu",
  "California State University, San Bernardino": "csusb.edu",
  "California State University, Stanislaus": "csustan.edu",
  "Calvin University": "calvin.edu",
  "Cameron University": "cameron.edu",
  "Campbell University": "campbell.edu",
  "Campbellsville University": "campbellsville.edu",
  "Canisius University": "canisius.edu",
  "Capital University": "capital.edu",
  "Carleton College": "carleton.edu",
  "Carlow University": "carlow.edu",
  "Carnegie Mellon University": "cmu.edu",
  "Carolina University": "coastal.edu",
  "Carroll College": "carroll.edu",
  "Carroll University": "carrollu.edu",
  "Carson\u2013Newman University": "cn.edu",
  "Carthage College": "carthage.edu",
  "Case Western Reserve University": "case.edu",
  "Catawba College": "catawba.edu",
  "Catholic University of America": "cua.edu",
  "Cedarville University": "cedarville.edu",
  "Centenary College of Louisiana": "centenary.edu",
  "Central College": "central.edu",
  "Central Connecticut State University": "ccsu.edu",
  "Central Methodist University": "cmc.edu",
  "Central Michigan University": "cmich.edu",
  "Central State University": "centralstate.edu",
  "Central Washington University": "cwu.edu",
  "Centre College": "centre.edu",
  "Chadron State College": "csc.edu",
  "Chaminade University of Honolulu": "chaminade.edu",
  "Chapman University": "chapman.edu",
  "Chatham University": "chatham.edu",
  "Chestnut Hill College": "hillcollege.edu",
  "Chicago State University": "csu.edu",
  "Christian Brothers University": "cbu.edu",
  "Christopher Newport University": "cnu.edu",
  "City College of New York": "cuny.edu",
  "Claflin University": "claflin.edu",
  "Claremont McKenna College, Harvey Mudd College, and Scripps College": "claremontmckenna.edu",
  "Clark Atlanta University": "cau.edu",
  "Clark University": "clarku.edu",
  "Clarke University": "clarke.edu",
  "Clarkson University|group=A|name='MH yes'": "clarkson.edu",
  "Clayton State University": "clayton.edu",
  "Clemson University": "clemson.edu",
  "Cleveland State University": "csuohio.edu",
  "Cloud County Community College": "cloud.edu",
  "Coastal Carolina University": "coastal.edu",
  "Coe College": "coe.edu",
  "Coffeyville Community College": "coffeyville.edu",
  "Coker University": "coker.edu",
  "Colby College": "colby.edu",
  "Colby Community College": "colbycc.edu",
  "Colgate University": "colgate.edu",
  "College of Charleston": "cofc.edu",
  "College of Idaho": "uidaho.edu",
  "College of Saint Benedict": "csbsju.edu",
  "College of Staten Island": "csi.cuny.edu",
  "College of Wooster": "wooster.edu",
  "College of the Holy Cross": "holycross.edu",
  "College of the Ozarks": "ozarks.edu",
  "Colorado Christian University": "ccu.edu",
  "Colorado College": "coloradocollege.edu",
  "Colorado Mesa University": "coloradomesa.edu",
  "Colorado School of Mines": "mines.edu",
  "Colorado State University": "colostate.edu",
  "Colorado State University\u2013Pueblo": "csupueblo.edu",
  "Columbia College (MO)": "ccis.edu",
  "Columbia College (SC)": "columbiasc.edu",
  "Columbia International University": "nu.edu",
  "Columbia University in the City of New York": "columbia.edu",
  "Columbus State University": "columbusstate.edu",
  "Concordia College": "ccaa.edu",
  "Concordia University Chicago": "uchicago.edu",
  "Concordia University Wisconsin": "cuw.edu",
  "Concordia University\u2013St. Paul": "csp.edu",
  "Connecticut College": "conncoll.edu",
  "Connors State College": "connorsstate.edu",
  "Coppin State University": "coppin.edu",
  "Cornell College": "cornell-iowa.edu",
  "Cornell University": "cornell.edu",
  "Covenant College": "covenant.edu",
  "Creighton University": "creighton.edu",
  "Crowder College": "crowder.edu",
  "Curry College": "curry.edu",
  "Daemen University": "daemen.edu",
  "Dakota State University": "dsu.edu",
  "Dakota Wesleyan University": "dwu.edu",
  "Dallas Baptist University": "dbu.edu",
  "Dalton State College": "daltonstate.edu",
  "Dartmouth College": "dartmouth.edu",
  "Davenport University": "davenport.edu",
  "Davidson College": "davidson.edu",
  "Davis & Elkins College": "dne.wvnet.edu",
  "DePaul University": "depaul.edu",
  "DePauw University": "depauw.edu",
  "Defiance College": "defiance.edu",
  "Delaware State University": "desu.edu",
  "Delaware Valley University": "delval.edu",
  "Delta State University": "deltastate.edu",
  "Denison University": "denison.edu",
  "Dickinson College": "dickinson.edu",
  "Dickinson State University": "dickinsonstate.edu",
  "Dillard University": "dillard.edu",
  "Doane College": "doane.edu",
  "Dodge City Community College": "dc3.edu",
  "Dominican University": "dom.edu",
  "Dominican University New York": "dom.edu",
  "Dominican University of California": "dom.edu",
  "Dordt University": "dordt.edu",
  "Drake University": "drake.edu",
  "Drew University": "drew.edu",
  "Drexel University": "drexel.edu",
  "Drury University": "drury.edu",
  "Duke University": "duke.edu",
  "Duquesne University of the Holy Spirit": "duq.edu",
  "Earlham College": "earlham.edu",
  "East Carolina University": "ecu.edu",
  "East Central University": "ecok.edu",
  "East Tennessee State University": "etsu.edu",
  "East Texas Baptist University": "etbu.edu",
  "Eastern Connecticut State University": "easternct.edu",
  "Eastern Illinois University": "eiu.edu",
  "Eastern Kentucky University": "eku.edu",
  "Eastern Mennonite University": "emu.edu",
  "Eastern Michigan University": "emich.edu",
  "Eastern New Mexico University": "enmu.edu",
  "Eastern Oklahoma State College": "eosc.edu",
  "Eastern University": "neu.edu",
  "Eastern Washington University": "ewu.edu",
  "Eckerd College": "eckerd.edu",
  "Edgewood University": "edgewood.edu",
  "Edward Waters University": "ewc.edu",
  "Elizabeth City State University": "ecsu.edu",
  "Elizabethtown College": "etown.edu",
  "Elmhurst University": "elmhurst.edu",
  "Elms College": "elms.edu",
  "Elon University": "elon.edu",
  "Embry\u2013Riddle Aeronautical University": "erau.edu",
  "Embry\u2013Riddle Aeronautical University, Prescott": "erau.edu",
  "Emerson College": "emerson.edu",
  "Emmanuel College": "emmanuel.edu",
  "Emmanuel University": "emmanuel.edu",
  "Emory & Henry University": "ehc.edu",
  "Emory University": "emory.edu",
  "Emporia State University": "emporia.edu",
  "Endicott College": "endicott.edu",
  "Fairfield University": "fairfield.edu",
  "Fairleigh Dickinson University": "fdu.edu",
  "Fairleigh Dickinson University, Florham": "fdu.edu",
  "Fairmont State University": "fairmontstate.edu",
  "Fayetteville State University": "uncfsu.edu",
  "Ferris State University": "ferris.edu",
  "Fisk University": "fisk.edu",
  "Fitchburg State University": "fsc.edu",
  "Florida Agricultural and Mechanical University": "famu.edu",
  "Florida Atlantic University": "fau.edu",
  "Florida Gulf Coast University": "fgcu.edu",
  "Florida Institute of Technology": "fit.edu",
  "Florida International University": "fiu.edu",
  "Florida Memorial University": "fmuniv.edu",
  "Florida National University": "nu.edu",
  "Florida Southern College": "flsouthern.edu",
  "Florida State University": "fsu.edu",
  "Fordham University": "fordham.edu",
  "Fort Hays State University": "fhsu.edu",
  "Fort Lewis College": "fortlewis.edu",
  "Fort Scott Community College": "fortscott.edu",
  "Fort Valley State University": "fvsu.edu",
  "Francis Marion University": "g.fmarion.edu",
  "Franklin & Marshall College": "fandm.edu",
  "Franklin College": "franklin.edu",
  "Franklin Pierce University": "franklinpierce.edu",
  "Fresno Pacific University": "fresno.edu",
  "Friends University": "friends.edu",
  "Frostburg State University": "frostburg.edu",
  "Furman University": "furman.edu",
  "Gallaudet University": "gallaudet.edu",
  "Gannon University": "gannon.edu",
  "Garden City Community College": "gcccks.edu",
  "Geneva College": "geneva.edu",
  "George Fox University": "georgefox.edu",
  "George Mason University": "gmu.edu",
  "Georgetown College": "georgetown.edu",
  "Georgetown University": "georgetown.edu",
  "Georgia College & State University": "gcsu.edu",
  "Georgia Gwinnett College": "ggc.edu",
  "Georgia Institute of Technology": "gatech.edu",
  "Georgia Southern University": "georgiasouthern.edu",
  "Georgia Southern University\u2013East Georgia Campus": "georgiasouthern.edu",
  "Georgia Southwestern State University": "gsw.edu",
  "Georgia State University": "gsu.edu",
  "Georgian Court University": "georgian.edu",
  "Gettysburg College": "gettysburg.edu",
  "Goldey\u2013Beacom College": "gbc.edu",
  "Gonzaga University": "gonzaga.edu",
  "Goshen College": "goshen.edu",
  "Goucher College": "goucher.edu",
  "Governors State University": "govst.edu",
  "Grace College & Seminary": "grace.edu",
  "Graceland University": "graceland.edu",
  "Grambling State University": "gram.edu",
  "Grand Canyon University": "gcu.edu",
  "Grand Valley State University": "gvsu.edu",
  "Grand View University": "grandview.edu",
  "Greensboro College": "greensboro.edu",
  "Greenville University": "greenville.edu",
  "Grinnell College": "grinnell.edu",
  "Guilford College": "guilford.edu",
  "Gustavus Adolphus College": "gac.edu",
  "Gwynedd Mercy University": "gmercyu.edu",
  "Hamilton College": "hamilton.edu",
  "Hamline University": "hamline.edu",
  "Hampden\u2013Sydney College": "hsc.edu",
  "Hampton University": "hamptonu.edu",
  "Hanover College": "hanover.edu",
  "Harding University": "harding.edu",
  "Harris\u2013Stowe State University": "hssu.edu",
  "Hartwick College": "hartwick.edu",
  "Harvard University": "harvard.edu",
  "Haskell Indian Nations University": "haskell.edu",
  "Hastings College": "hastings.edu",
  "Haverford College": "haverford.edu",
  "Hawai'i Pacific University": "pacificu.edu",
  "Heidelberg University": "heidelberg.edu",
  "Hendrix College": "hendrix.edu",
  "Hesston College": "hesston.edu",
  "High Point University": "highpoint.edu",
  "Highland Community College": "highland.edu",
  "Hillsdale College": "hillsdale.edu",
  "Hiram College": "hiram.edu",
  "Hofstra University": "hofstra.edu",
  "Hollins University": "hollins.edu",
  "Hood College": "hood.edu",
  "Hope College": "hope.edu",
  "Hope International University": "nu.edu",
  "Howard University": "howard.edu",
  "Hunter College": "hunter.cuny.edu",
  "Huntingdon College": "huntingdon.edu",
  "Huntington University": "huntington.edu",
  "Huston\u2013Tillotson University": "htu.edu",
  "Hutchinson Community College": "hutchcc.edu",
  "Idaho State University": "isu.edu",
  "Illinois College": "sic.edu",
  "Illinois Institute of Technology": "iit.edu",
  "Illinois State University": "illinoisstate.edu",
  "Illinois Wesleyan University": "iwu.edu",
  "Independence Community College": "indycc.edu",
  "Indian Hills Community College": "indianhills.edu",
  "Indiana Institute of Technology (Indiana Tech)": "indianatech.edu",
  "Indiana State University": "indstate.edu",
  "Indiana University Bloomington": "indiana.edu",
  "Indiana University Columbus (IU Columbus)": "iu.edu",
  "Indiana University East (IU East)": "iu.edu",
  "Indiana University Indianapolis": "iu.edu",
  "Indiana University Kokomo (IU Kokomo)": "iu.edu",
  "Indiana University Northwest (IU Northwest)": "iu.edu",
  "Indiana University South Bend (IU South Bend)": "iu.edu",
  "Indiana University Southeast (IU Southeast or IUS)": "iu.edu",
  "Indiana University of Pennsylvania": "iup.edu",
  "Indiana Wesleyan University": "indwes.edu",
  "Iona University": "iona.edu",
  "Iowa State University of Science and Technology": "iastate.edu",
  "Iowa Western Community College": "iwcc.edu",
  "Ithaca College": "ithaca.edu",
  "Jackson State University": "jsums.edu",
  "Jacksonville State University": "jsu.edu",
  "Jacksonville University": "ju.edu",
  "James Madison University": "jmu.edu",
  "Jarvis Christian University": "jarvis.edu",
  "Jefferson College": "jeffco.edu",
  "John Brown University": "jbu.edu",
  "John Carroll University": "carrollu.edu",
  "John Jay College of Criminal Justice": "jjay.cuny.edu",
  "Johns Hopkins University": "jh.edu",
  "Johnson & Wales University": "jwu.edu",
  "Johnson & Wales University Charlotte": "jwu.edu",
  "Johnson C. Smith University": "jcsu.edu",
  "Johnson County Community College": "jccc.edu",
  "Judson University": "judson.edu",
  "Juniata College": "juniata.edu",
  "Kalamazoo College": "kzoo.edu",
  "Kansas City Kansas Community College": "kckcc.edu",
  "Kansas State University": "ksu.edu",
  "Kansas Wesleyan University": "kwu.edu",
  "Kean University": "kean.edu",
  "Keene State College": "keene.edu",
  "Keiser University": "keiseruniversity.edu",
  "Kennesaw State University": "kennesaw.edu",
  "Kent State University": "kent.edu",
  "Kentucky State University": "kysu.edu",
  "Kenyon College": "kenyon.edu",
  "King University": "king.edu",
  "King's College": "kings.edu",
  "Kirkwood Community College": "kirkwood.edu",
  "Knox College": "knox.edu",
  "Kutztown University": "kutztown.edu",
  "La Sierra University": "lasierra.edu",
  "LaGrange College": "lagrange.edu",
  "Labette Community College": "labette.edu",
  "Lackawanna College": "lackawanna.edu",
  "Lafayette College": "lafayette.edu",
  "Lake Erie College": "lecom.edu",
  "Lake Forest College": "lfc.edu",
  "Lake Superior State University": "lssu.edu",
  "Lamar University": "lamar.edu",
  "Lander University": "lander.edu",
  "Lane College": "lanecollege.edu",
  "Langston University": "langston.edu",
  "Lasell University": "lasell.edu",
  "Lawrence Technological University(Lawrence Tech)": "ltu.edu",
  "Lawrence University": "lawrence.edu",
  "Le Moyne College": "lemoyne.edu",
  "LeMoyne\u2013Owen College": "loc.edu",
  "LeTourneau University": "letu.edu",
  "Lebanon Valley College": "lvc.edu",
  "Lee University": "lee.edu",
  "Lehigh University": "lehigh.edu",
  "Lehman College": "lehman.cuny.edu",
  "Lenoir\u2013Rhyne University": "lr.edu",
  "Lesley University": "lesley.edu",
  "Lewis & Clark College": "lclark.edu",
  "Lewis University": "lewisu.edu",
  "Lewis\u2013Clark State College": "lcsc.edu",
  "Liberty University": "liberty.edu",
  "Life Pacific University": "pacificu.edu",
  "Lincoln Memorial University": "lmunet.edu",
  "Lincoln University (MO)": "lincoln.edu",
  "Lincoln University (PA)": "lincoln.edu",
  "Lindenwood University": "lindenwood.edu",
  "Linfield University": "linfield.edu",
  "Lipscomb University": "lipscomb.edu",
  "Livingstone College": "livingstone.edu",
  "Long Island University": "liunet.edu",
  "Longwood University": "longwood.edu",
  "Loras College": "loras.edu",
  "Louisiana State University New Orleans": "lsu.edu",
  "Louisiana State University and Agricultural and Mechanical College": "lsu.edu",
  "Louisiana State University at Alexandria (LSU Alexandria)": "lsu.edu",
  "Louisiana State University in Shreveport (LSU Shreveport)": "lsu.edu",
  "Louisiana Tech University": "latech.edu",
  "Loyola Marymount University": "lmu.edu",
  "Loyola University Chicago": "luc.edu",
  "Loyola University New Orleans": "loyno.edu",
  "Luther College": "luther.edu",
  "Lycoming College": "lycoming.edu",
  "Lynn University": "lynn.edu",
  "Lyon College": "lyon.edu",
  "Macalester College": "macalester.edu",
  "Malone University": "malone.edu",
  "Manhattan University": "manhattan.edu",
  "Marietta College": "marietta.edu",
  "Marist University": "marist.edu",
  "Marquette University": "marquette.edu",
  "Marshall University": "marshall.edu",
  "Martin Luther College": "luther.edu",
  "Mary Baldwin University": "mbc.edu",
  "Marymount University": "marymount.edu",
  "Maryville College": "maryvillecollege.edu",
  "Maryville University": "maryville.edu",
  "Marywood University": "marywood.edu",
  "Massachusetts Institute of Technology": "mit.edu",
  "McDaniel College": "mcdaniel.edu",
  "McMurry University": "mcm.edu",
  "McNeese State University": "mcneese.edu",
  "McPherson College": "mcpherson.edu",
  "Medgar Evers College": "mec.cuny.edu",
  "Mercer University": "mercer.edu",
  "Mercy University": "mercymavericks.edu",
  "Mercyhurst University": "mercyhurst.edu",
  "Meredith College": "meredith.edu",
  "Merrimack College": "merrimack.edu",
  "Messiah University": "messiah.edu",
  "Methodist University": "smu.edu",
  "Metropolitan Community College": "mcckc.edu",
  "Metropolitan State University of Denver": "msudenver.edu",
  "Miami University": "miamioh.edu",
  "Michigan State University": "msu.edu",
  "Michigan Technological University": "mtu.edu",
  "Middle Georgia State University": "mga.edu",
  "Middle Tennessee State University": "mtsu.edu",
  "Middlebury College": "middlebury.edu",
  "Midwestern State University": "mwsu.edu",
  "Miles College": "miles.edu",
  "Millersville University": "millersville.edu",
  "Milligan University": "milligan.edu",
  "Millikin University": "millikin.edu",
  "Millsaps College": "millsaps.edu",
  "Milwaukee School of Engineering": "msoe.edu",
  "Mineral Area College": "mineralarea.edu",
  "Minnesota State University Moorhead": "mnstate.edu",
  "Minnesota State University, Mankato": "mnsu.edu",
  "Minot State University": "minotstateu.edu",
  "Mission University": "missioncollege.edu",
  "Mississippi State University": "msstate.edu",
  "Mississippi University for Women": "muw.edu",
  "Mississippi Valley State University": "mvsu.edu",
  "Missouri Southern State University": "mssc.edu",
  "Missouri State University": "missouristate.edu",
  "Missouri University of Science and Technology": "mst.edu",
  "Missouri Western State University": "mwsc.edu",
  "Mitchell College": "wmitchell.edu",
  "Moberly Area Community College": "macc.edu",
  "Molloy University": "molloy.edu",
  "Monmouth College": "monmouthcollege.edu",
  "Monmouth University": "monmouth.edu",
  "Monroe University": "monroecollege.edu",
  "Montana State University": "msubillings.edu",
  "Montana State University Billings": "msubillings.edu",
  "Montana State University\u2013Northern": "msun.edu",
  "Montana Technological University(Montana Tech)": "mtech.edu",
  "Montclair State University": "montclair.edu",
  "Montreat College": "montreat.edu",
  "Moravian University": "moravian.edu",
  "Morehead State University": "moreheadstate.edu",
  "Morehouse College": "morehouse.edu",
  "Morgan State University": "morgan.edu",
  "Morris College": "morris.edu",
  "Mount Holyoke College": "mtholyoke.edu",
  "Mount Saint Mary College": "msmc.edu",
  "Murray State University": "mursuky.edu",
  "Muskingum University": "muskingum.edu",
  "Nazareth University": "naz.edu",
  "Nebraska Wesleyan University": "nebrwesleyan.edu",
  "Neosho County Community College": "neosho.edu",
  "Neumann University": "neumann.edu",
  "New College of Florida": "ncf.edu",
  "New England College": "wnec.edu",
  "New Jersey Institute of Technology": "njit.edu",
  "New Mexico Highlands University": "nmhu.edu",
  "New Mexico State University": "nmsu.edu",
  "New York University": "nyu.edu",
  "Newberry College": "newberry.edu",
  "Niagara University": "niagara.edu",
  "Nicholls State University": "nicholls.edu",
  "Norfolk State University": "nsu.edu",
  "North American University": "na.edu",
  "North Carolina Central University": "nccu.edu",
  "North Carolina State University": "ncsu.edu",
  "North Carolina Wesleyan University": "ncwc.edu",
  "North Central College": "northcentralcollege.edu",
  "North Central Missouri College": "ncmissouri.edu",
  "North Central University": "northcentralcollege.edu",
  "North Dakota State University of Agriculture and Applied Sciences": "dsu.edu",
  "North Greenville University": "greenville.edu",
  "North Park University": "park.edu",
  "Northeast Community College": "northeast.edu",
  "Northeastern Oklahoma A&M College": "neo.edu",
  "Northeastern State University": "nsuok.edu",
  "Northeastern University": "neu.edu",
  "Northern Arizona University": "nau.edu",
  "Northern Illinois University": "niu.edu",
  "Northern Kentucky University": "nku.edu",
  "Northern Michigan University": "nmu.edu",
  "Northern State University": "northern.edu",
  "Northwest Missouri State University": "nwmissouri.edu",
  "Northwest Nazarene University": "nnc.edu",
  "Northwest University": "northwestcollege.edu",
  "Northwestern College": "northwestern.edu",
  "Northwestern Oklahoma State University": "okstate.edu",
  "Northwestern State University of Louisiana": "nsula.edu",
  "Northwestern University": "northwestern.edu",
  "Northwood University": "northwood.edu",
  "Norwich University": "norwich.edu",
  "Nova Southeastern University": "nova.edu",
  "Oakland University": "oakland.edu",
  "Oakwood University": "oakwood.edu",
  "Oberlin College": "oberlin.edu",
  "Occidental College": "oxy.edu",
  "Oglethorpe University": "oglethorpe.edu",
  "Ohio Dominican University": "odc.edu",
  "Ohio Northern University": "onu.edu",
  "Ohio Wesleyan University": "owu.edu",
  "Oklahoma Baptist University": "okbu.edu",
  "Oklahoma Christian University": "oc.edu",
  "Oklahoma City University": "okcu.edu",
  "Oklahoma State University\u2013Stillwater": "okstate.edu",
  "Oklahoma Wesleyan University": "wesleyan.edu",
  "Old Dominion University": "odu.edu",
  "Olivet Nazarene University": "olivet.edu",
  "Oral Roberts University": "oru.edu",
  "Oregon Institute of Technology(Oregon Tech)": "oit.edu",
  "Oregon State University": "oregonstate.edu",
  "Ottawa University Arizona (OUAZ)": "arizona.edu",
  "Otterbein University": "otterbein.edu",
  "Our Lady of the Lake University": "ollusa.edu",
  "Pace University": "pace.edu",
  "Pacific Lutheran University": "plu.edu",
  "Pacific Union College": "puc.edu",
  "Pacific University": "pacificu.edu",
  "Palm Beach Atlantic University": "pbac.edu",
  "Park University": "park.edu",
  "Park University Gilbert": "park.edu",
  "Paul Quinn College": "paulquinn.edu",
  "Pennsylvania College of Technology": "pct.edu",
  "Pennsylvania State University, Abington": "psu.edu",
  "Pennsylvania State University, Altoona": "psu.edu",
  "Pennsylvania State University, Behrend": "psu.edu",
  "Pennsylvania State University, Berks College": "psu.edu",
  "Pennsylvania State University, Brandywine": "psu.edu",
  "Pennsylvania State University, Harrisburg": "harrisburg.psu.edu",
  "Pepperdine University": "pepperdine.edu",
  "Peru State College": "peru.edu",
  "Philander Smith University": "philander.edu",
  "Pittsburg State University": "pittstate.edu",
  "Plymouth State University": "plymouth.edu",
  "Point Park University": "pointpark.edu",
  "Point University": "highpoint.edu",
  "Pomona College and Pitzer College": "pitzer.edu",
  "Portland State University": "pdx.edu",
  "Prairie View A&M University": "pvamu.edu",
  "Pratt Community College": "prattcc.edu",
  "Pratt Institute": "pratt.edu",
  "Presbyterian College": "presby.edu",
  "Princeton University": "princeton.edu",
  "Principia College": "principia.edu",
  "Providence College": "providence.edu",
  "Purdue University": "purdue.edu",
  "Purdue University Fort Wayne": "pfw.edu",
  "Purdue University Northwest": "pnw.edu",
  "Queens College": "qc.cuny.edu",
  "Queens University of Charlotte": "queens.edu",
  "Quincy University": "quincy.edu",
  "Quinnipiac University": "quinnipiac.edu",
  "Radford University": "radford.edu",
  "Ramapo College": "ramapo.edu",
  "Randolph\u2013Macon College": "rmc.edu",
  "Redlands Community College": "redlandscc.edu",
  "Regent University": "regent.edu",
  "Regis College": "regis.edu",
  "Regis University": "regis.edu",
  "Rensselaer Polytechnic Institute": "rpi.edu",
  "Rhode Island College": "ric.edu",
  "Rhodes College": "rhodes.edu",
  "Rider University": "rider.edu",
  "Ripon College": "ripon.edu",
  "Rivier University": "riv.edu",
  "Roanoke College": "roanoke.edu",
  "Robert Morris University": "rmu.edu",
  "Roberts Wesleyan University": "wesleyan.edu",
  "Rochester Institute of Technology": "rit.edu",
  "Rockford University": "rockford.edu",
  "Rockhurst University": "rockhurst.edu",
  "Rocky Mountain College": "rocky.edu",
  "Roger Williams University": "rwu.edu",
  "Rogers State University": "rsu.edu",
  "Rollins College": "rollins.edu",
  "Roosevelt University": "roosevelt.edu",
  "Rose-Hulman Institute of Technology": "rose-hulman.edu",
  "Rowan University": "rowan.edu",
  "Rust College": "rustcollege.edu",
  "Rutgers University\u2013Camden": "rutgers.edu",
  "Rutgers University\u2013New Brunswick": "rutgers.edu",
  "Rutgers University\u2013Newark": "rutgers.edu",
  "Sacred Heart University": "sacredheart.edu",
  "Saginaw Valley State University": "svsu.edu",
  "Saint Anselm College": "anselm.edu",
  "Saint John's University": "stjohns.edu",
  "Saint Joseph's University": "sju.edu",
  "Saint Leo University": "saintleo.edu",
  "Saint Louis University": "slu.edu",
  "Saint Mary's College": "saintmarys.edu",
  "Saint Mary's College of California": "stmarys-ca.edu",
  "Saint Mary's University of Minnesota": "smumn.edu",
  "Saint Michael's College": "smcvt.edu",
  "Saint Vincent College": "stvincent.edu",
  "Saint Xavier University": "sxu.edu",
  "Salem State University": "wssu.edu",
  "Salisbury University": "salisbury.edu",
  "Sam Houston State University": "shsu.edu",
  "Samford University": "samford.edu",
  "San Diego State University": "sdsu.edu",
  "San Francisco State University": "sfsu.edu",
  "San Jose State University": "sjsu.edu",
  "Santa Clara University": "scu.edu",
  "Sarah Lawrence College": "slc.edu",
  "Savannah College of Art and Design*": "scad.edu",
  "Savannah State University": "savannahstate.edu",
  "Schreiner University": "schreiner.edu",
  "Seattle Pacific University": "spu.edu",
  "Seattle University": "seattleu.edu",
  "Seminole State College": "sscok.edu",
  "Seton Hall University": "shu.edu",
  "Seward County Community College": "sccc.edu",
  "Shaw University": "shawu.edu",
  "Shawnee State University": "shawnee.edu",
  "Shenandoah University": "su.edu",
  "Shippensburg University": "ship.edu",
  "Shorter University": "shorter.edu",
  "Siena University": "siena.edu",
  "Simmons University": "simmons.edu",
  "Simpson College": "simpson.edu",
  "Simpson University": "simpson.edu",
  "Skidmore College": "skidmore.edu",
  "Slippery Rock University": "sru.edu",
  "Smith College": "smith.edu",
  "South Carolina State University": "scsu.edu",
  "South Dakota School of Mines and Technology": "sdsmt.edu",
  "South Dakota State University": "sdstate.edu",
  "Southeast Community College": "southeast.edu",
  "Southeast Missouri State University": "semo.edu",
  "Southeastern Community College": "scciowa.edu",
  "Southeastern Louisiana University": "selu.edu",
  "Southeastern Oklahoma State University": "okstate.edu",
  "Southeastern University": "nova.edu",
  "Southern Arkansas University": "sautech.edu",
  "Southern Connecticut State University": "southernct.edu",
  "Southern Illinois University Carbondale": "siu.edu",
  "Southern Illinois University Edwardsville": "siue.edu",
  "Southern Methodist University": "smu.edu",
  "Southern Nazarene University": "snu.edu",
  "Southern New Hampshire University": "snhu.edu",
  "Southern University and A&M College": "subr.edu",
  "Southern University at New Orleans (SUNO)": "uno.edu",
  "Southern Utah University": "suu.edu",
  "Southern Virginia University": "svu.edu",
  "Southern Wesleyan University": "wesleyan.edu",
  "Southwest Baptist University": "sbuniv.edu",
  "Southwest Minnesota State University": "smsu.edu",
  "Southwestern Christian University": "swcc.edu",
  "Southwestern College": "southwestern.edu",
  "Southwestern Oklahoma State University": "okstate.edu",
  "Southwestern University": "southwestern.edu",
  "Spartanburg Methodist College": "smcsc.edu",
  "Spring Arbor University": "arbor.edu",
  "Spring Hill College": "shc.edu",
  "St. Ambrose University": "sau.edu",
  "St. Lawrence University": "stlawu.edu",
  "St. Mary's College of Maryland": "smcm.edu",
  "St. Mary's University": "stmarytx.edu",
  "St. Thomas Aquinas College": "aquinas.edu",
  "St. Thomas University": "stu.edu",
  "State Fair Community College": "sfccmo.edu",
  "State University of Iowa": "uiowa.edu",
  "State University of New York Polytechnic Institute": "sunyit.edu",
  "State University of New York at Albany": "albany.edu",
  "State University of New York at Binghamton": "binghamton.edu",
  "State University of New York at Buffalo": "buffalo.edu",
  "State University of New York at Fredonia": "fredonia.edu",
  "State University of New York at Oneonta": "suny.oneonta.edu",
  "State University of New York at Oswego": "oswego.edu",
  "State University of New York at Plattsburgh": "plattsburgh.edu",
  "State University of New York at Stony Brook": "stonybrook.edu",
  "Stephen F. Austin State University": "sfasu.edu",
  "Stephens College": "stephens.edu",
  "Stetson University": "stetson.edu",
  "Stevens Institute of Technology": "stevens.edu",
  "Stevenson University": "stevenson.edu",
  "Stillman College": "stillman.edu",
  "Stonehill College": "stonehill.edu",
  "Suffolk University": "suffolk.edu",
  "Sul Ross State University": "sulross.edu",
  "Susquehanna University": "susqu.edu",
  "Swarthmore College": "swarthmore.edu",
  "Sweet Briar College": "sbc.edu",
  "Syracuse University": "syr.edu",
  "Tabor College": "tabor.edu",
  "Talladega College": "talladega.edu",
  "Tarleton State University": "tarleton.edu",
  "Taylor University": "tayloru.edu",
  "Temple University": "temple.edu",
  "Tennessee State University": "tnstate.edu",
  "Tennessee Technological University": "tntech.edu",
  "Tennessee Wesleyan University": "wesleyan.edu",
  "Texas A&M International University": "tamiu.edu",
  "Texas A&M University": "tamu.edu",
  "Texas A&M University\u2013Corpus Christi": "tamucc.edu",
  "Texas A&M University\u2013Kingsville": "tamuk.edu",
  "Texas A&M University\u2013Texarkana": "ace.tamut.edu",
  "Texas Christian University": "tcu.edu",
  "Texas College": "texascollege.edu",
  "Texas Southern University": "tsu.edu",
  "Texas State University": "txstate.edu",
  "Texas Tech University": "ttu.edu",
  "Texas Wesleyan University": "txwes.edu",
  "Texas Woman's University": "twu.edu",
  "The Citadel, The Military College of South Carolina": "citadel.edu",
  "The College of New Jersey": "tcnj.edu",
  "The College of St. Scholastica": "css.edu",
  "The College of William and Mary in Virginia": "wm.edu",
  "The Evergreen State College": "evergreen.edu",
  "The George Washington University": "gwu.edu",
  "The Ohio State University": "osu.edu",
  "The Ohio University": "ohio.edu",
  "The Pennsylvania State University": "psu.edu",
  "The University of Akron": "uakron.edu",
  "The University of Alabama": "ua.edu",
  "The University of Mississippi": "olemiss.edu",
  "The University of New Mexico": "unm.edu",
  "The University of Tennessee at Chattanooga": "utc.edu",
  "The University of Tennessee at Martin": "utm.edu",
  "The University of Tennessee, Knoxville": "utk.edu",
  "The University of Texas Rio Grande Valley": "utrgv.edu",
  "The University of Texas at Arlington": "uta.edu",
  "The University of Texas at Austin": "utexas.edu",
  "The University of Texas at El Paso": "utep.edu",
  "The University of Texas at San Antonio": "utsa.edu",
  "The University of Tulsa": "utulsa.edu",
  "The University of Vermont and State Agricultural College": "uvm.edu",
  "Thomas College": "thomas.edu",
  "Thomas Jefferson University": "tju.edu",
  "Thomas More University": "thomasmore.edu",
  "Thomas University": "thomas.edu",
  "Tiffin University": "tiffin.edu",
  "Tougaloo College": "tougaloo.edu",
  "Towson University": "towson.edu",
  "Transylvania University": "transy.edu",
  "Trine University": "trine.edu",
  "Trinity College": "trinity.edu",
  "Trinity University": "trinity.edu",
  "Troy University": "troy.edu",
  "Truman State University": "truman.edu",
  "Tufts University": "tufts.edu",
  "Tulane University of Louisiana": "tulane.edu",
  "Tusculum University": "tusculum.edu",
  "Tuskegee University": "tuskegee.edu",
  "Union College": "union.edu",
  "Union University": "uu.edu",
  "United States Air Force Academy": "usafa.af.mil",
  "United States Coast Guard Academy": "uscga.edu",
  "United States Merchant Marine Academy": "usmma.edu",
  "United States Military Academy": "usma.edu",
  "United States Naval Academy": "usna.edu",
  "University of Alabama at Birmingham": "uab.edu",
  "University of Alabama in Huntsville": "ua.edu",
  "University of Alaska Anchorage": "uaa.alaska.edu",
  "University of Alaska Fairbanks": "uaf.edu",
  "University of Arizona": "arizona.edu",
  "University of Arkansas": "uasys.edu",
  "University of Arkansas at Little Rock": "ualr.edu",
  "University of Arkansas at Monticello": "uamont.edu",
  "University of Arkansas\u2013Fort Smith": "uafs.edu",
  "University of Bridgeport": "bridgeport.edu",
  "University of California, Berkeley": "berkeley.edu",
  "University of California, Davis": "ucdavis.edu",
  "University of California, Irvine": "uci.edu",
  "University of California, Los Angeles": "ucla.edu",
  "University of California, Merced": "ucmerced.edu",
  "University of California, Riverside": "ucr.edu",
  "University of California, San Diego": "ucsd.edu",
  "University of California, Santa Barbara": "ucsb.edu",
  "University of California, Santa Cruz": "ucsc.edu",
  "University of Central Arkansas": "uca.edu",
  "University of Central Florida": "ucf.edu",
  "University of Central Missouri": "ucmo.edu",
  "University of Central Oklahoma": "uco.edu",
  "University of Charleston": "uchaswv.edu",
  "University of Chicago": "uchicago.edu",
  "University of Cincinnati": "uc.edu",
  "University of Colorado Boulder": "colorado.edu",
  "University of Colorado Colorado Springs": "uccs.edu",
  "University of Connecticut": "uconn.edu",
  "University of Dallas": "udallas.edu",
  "University of Dayton": "udayton.edu",
  "University of Delaware": "udel.edu",
  "University of Denver": "du.edu",
  "University of Detroit Mercy": "udmercy.edu",
  "University of Dubuque": "dbq.edu",
  "University of Evansville": "evansville.edu",
  "University of Findlay": "findlay.edu",
  "University of Florida": "ufl.edu",
  "University of Georgia": "uga.edu",
  "University of Hartford": "hartford.edu",
  "University of Houston": "uh.edu",
  "University of Idaho": "uidaho.edu",
  "University of Illinois Chicago": "uic.edu",
  "University of Illinois Urbana-Champaign": "uiuc.edu",
  "University of Illinois at Springfield": "uis.edu",
  "University of Indianapolis": "uindy.edu",
  "University of Jamestown": "uj.edu",
  "University of Kansas": "ku.edu",
  "University of Kentucky": "uky.edu",
  "University of La Verne": "laverne.edu",
  "University of Louisiana at Monroe": "ulm.edu",
  "University of Louisville": "louisville.edu",
  "University of Lynchburg": "vul.edu",
  "University of Maine": "umaine.edu",
  "University of Maine at Augusta": "umaine.edu",
  "University of Maine at Farmington": "umf.maine.edu",
  "University of Maine at Presque Isle": "umaine.edu",
  "University of Mary": "umw.edu",
  "University of Mary Washington": "umw.edu",
  "University of Maryland Eastern Shore": "umes.edu",
  "University of Maryland, Baltimore County": "umbc.edu",
  "University of Maryland, College Park": "umd.edu",
  "University of Massachusetts Amherst": "umass.edu",
  "University of Massachusetts Boston": "umb.edu",
  "University of Massachusetts Dartmouth": "umassd.edu",
  "University of Massachusetts Lowell": "uml.edu",
  "University of Memphis": "memphis.edu",
  "University of Miami": "miami.edu",
  "University of Michigan": "umich.edu",
  "University of Michigan\u2013Dearborn": "umdearborn.edu",
  "University of Minnesota": "umn.edu",
  "University of Minnesota Crookston": "crk.umn.edu",
  "University of Minnesota Duluth": "d.umn.edu",
  "University of Minnesota Morris": "mrs.umn.edu",
  "University of Missouri\u2013Columbia": "missouri.edu",
  "University of Missouri\u2013Kansas City": "umkc.edu",
  "University of Missouri\u2013St. Louis": "missouri.edu",
  "University of Montana": "umt.edu",
  "University of Montana\u2013Western": "umwestern.edu",
  "University of Mount Olive": "umo.edu",
  "University of Mount Saint Vincent": "mountsaintvincent.edu",
  "University of Nebraska Omaha": "unomaha.edu",
  "University of Nebraska at Kearney": "unk.edu",
  "University of Nebraska\u2013Lincoln": "unl.edu",
  "University of Nevada, Las Vegas": "unlv.edu",
  "University of Nevada, Reno": "unr.edu",
  "University of New England": "une.edu",
  "University of New Hampshire": "unh.edu",
  "University of New Haven": "newhaven.edu",
  "University of North Alabama": "una.edu",
  "University of North Carolina at Asheville": "unca.edu",
  "University of North Carolina at Chapel Hill": "unc.edu",
  "University of North Carolina at Charlotte": "uncc.edu",
  "University of North Carolina at Greensboro": "uncg.edu",
  "University of North Carolina at Wilmington": "uncw.edu",
  "University of North Dakota": "und.edu",
  "University of North Florida": "unf.edu",
  "University of North Georgia": "ung.edu",
  "University of North Texas": "unt.edu",
  "University of North Texas at Dallas": "untdallas.edu",
  "University of Northern Colorado": "unco.edu",
  "University of Northern Iowa": "uni.edu",
  "University of Notre Dame du Lac": "nd.edu",
  "University of Oklahoma": "ou.edu",
  "University of Olivet": "olivetcollege.edu",
  "University of Oregon": "uoregon.edu",
  "University of Pennsylvania": "upenn.edu",
  "University of Pikeville": "upike.edu",
  "University of Pittsburgh": "pitt.edu",
  "University of Pittsburgh at Bradford": "upb.pitt.edu",
  "University of Pittsburgh at Greensburg": "pitt.edu",
  "University of Pittsburgh at Johnstown": "upj.pitt.edu",
  "University of Portland": "up.edu",
  "University of Puerto Rico at Bayam\u00f3n": "upr.edu",
  "University of Puerto Rico at Mayag\u00fcez": "upr.edu",
  "University of Puerto Rico at R\u00edo Piedras": "upr.edu",
  "University of Puget Sound": "ups.edu",
  "University of Redlands": "uor.edu",
  "University of Rhode Island": "uri.edu",
  "University of Richmond": "urich.edu",
  "University of Rochester": "rochester.edu",
  "University of Saint Thomas": "stthomas.edu",
  "University of San Diego": "sandiego.edu",
  "University of San Francisco": "usfca.edu",
  "University of Science and Arts of Oklahoma": "usao.edu",
  "University of Scranton": "scranton.edu",
  "University of Sioux Falls": "usouixfalls.edu",
  "University of South Alabama": "southalabama.edu",
  "University of South Carolina": "sc.edu",
  "University of South Carolina Aiken": "usca.edu",
  "University of South Carolina Beaufort": "uscb.edu",
  "University of South Carolina Upstate": "email.uscupstate.edu",
  "University of South Dakota": "usd.edu",
  "University of South Florida": "usf.edu",
  "University of Southern California": "usc.edu",
  "University of Southern Indiana": "usi.edu",
  "University of Southern Maine": "usm.maine.edu",
  "University of Southern Mississippi": "usm.edu",
  "University of St. Francis": "stfrancis.edu",
  "University of Tampa": "ut.edu",
  "University of Texas Permian Basin": "utpb.edu",
  "University of Texas at Dallas": "utd.edu",
  "University of Texas at Tyler": "uttyler.edu",
  "University of Toledo": "utoledo.edu",
  "University of Utah": "utah.edu",
  "University of Virginia": "virginia.edu",
  "University of Washington": "uw.edu",
  "University of West Alabama": "westal.edu",
  "University of West Florida": "uwf.edu",
  "University of West Georgia": "westga.edu",
  "University of Wisconsin\u2013Eau Claire": "uwec.edu",
  "University of Wisconsin\u2013Green Bay": "uwgb.edu",
  "University of Wisconsin\u2013Madison": "wisc.edu",
  "University of Wisconsin\u2013Milwaukee": "uwm.edu",
  "University of Wisconsin\u2013Oshkosh": "uwosh.edu",
  "University of Wisconsin\u2013Parkside": "uwp.edu",
  "University of Wisconsin\u2013Platteville": "uwplatt.edu",
  "University of Wisconsin\u2013River Falls": "uwrf.edu",
  "University of Wisconsin\u2013Stevens Point": "uwsp.edu",
  "University of Wisconsin\u2013Stout": "uwstout.edu",
  "University of Wisconsin\u2013Superior": "uwsuper.edu",
  "University of Wisconsin\u2013Whitewater": "uww.edu",
  "University of Wyoming": "uwyo.edu",
  "University of the District of Columbia": "udc.edu",
  "University of the Incarnate Word": "uiw.edu",
  "University of the Ozarks": "ozarks.edu",
  "University of the Pacific": "uop.edu",
  "University of the South": "iusb.edu",
  "University of the Southwest": "usl.edu",
  "Upper Iowa University": "uiu.edu",
  "Ursinus College": "ursinus.edu",
  "Utah State University": "usu.edu",
  "Utah Tech University": "utahtech.edu",
  "Utah Valley University": "uvu.edu",
  "Utica University": "utica.edu",
  "Valdosta State University": "valdosta.edu",
  "Valley City State University": "vcsu.edu",
  "Valparaiso University": "valpo.edu",
  "Vanderbilt University": "vanderbilt.edu",
  "Vassar College": "vassar.edu",
  "Villanova University": "villanova.edu",
  "Virginia Commonwealth University": "vcu.edu",
  "Virginia Military Institute": "vmi.edu",
  "Virginia State University": "vsu.edu",
  "Virginia Union University": "vuu.edu",
  "Voorhees University": "voorhees.edu",
  "Wabash College": "wabash.edu",
  "Wagner College": "wagner.edu",
  "Wake Forest University": "wfu.edu",
  "Walla Walla University": "wallawalla.edu",
  "Walsh University": "walshcollege.edu",
  "Warner Pacific University": "pacificu.edu",
  "Warren Wilson College": "warren-wilson.edu",
  "Wartburg College": "wartburg.edu",
  "Washburn University": "wuacc.edu",
  "Washington & Jefferson College": "washjeff.edu",
  "Washington College": "washcoll.edu",
  "Washington State University": "wsu.edu",
  "Washington and Lee University": "wlu.edu",
  "Wayland Baptist University": "wbu.edu",
  "Wayne State College": "wayne.edu",
  "Wayne State University": "wayne.edu",
  "Waynesburg University": "waynesburg.edu",
  "Webber International University": "nu.edu",
  "Weber State University": "weber.edu",
  "Webster University": "webster.edu",
  "Wellesley College": "wellesley.edu",
  "Wentworth Institute of Technology": "wit.edu",
  "Wesleyan College": "wesleyan.edu",
  "Wesleyan University": "wesleyan.edu",
  "West Chester University": "wcupa.edu",
  "West Liberty University": "liberty.edu",
  "West Texas A&M University": "wtamu.edu",
  "West Virginia State University": "wvstate.edu",
  "West Virginia University": "wvu.edu",
  "West Virginia University Institute of Technology (WVU Tech)": "wvu.edu",
  "West Virginia Wesleyan College": "wvwc.edu",
  "Western Carolina University": "wcu.edu",
  "Western Connecticut State University": "wcsu.edu",
  "Western Illinois University": "wiu.edu",
  "Western Kentucky University": "wku.edu",
  "Western Michigan University": "wmich.edu",
  "Western Nebraska Community College": "wncc.edu",
  "Western New England University": "wne.edu",
  "Western New Mexico University": "wnmu.edu",
  "Western Washington University": "wwu.edu",
  "Westfield State University": "westfield.mass.edu",
  "Westminster College": "westminsteru.edu",
  "Westminster University": "westminsteru.edu",
  "Westmont College": "westmont.edu",
  "Wheaton College": "wheaton.edu",
  "Whitman College": "whitman.edu",
  "Whittier College": "whittier.edu",
  "Whitworth University": "whitworth.edu",
  "Wichita State University": "wichita.edu",
  "Widener University": "widener.edu",
  "Wilberforce University": "wilberforce.edu",
  "Wiley University": "wileyc.edu",
  "Wilkes University": "wilkes.edu",
  "Willamette University": "willamette.edu",
  "William Jewell College": "jewell.edu",
  "William Marsh Rice University": "rice.edu",
  "William Paterson University": "wpunj.edu",
  "William Penn University": "wmpenn.edu",
  "William Smith College": "hws.edu",
  "William Woods University": "wmwoods.edu",
  "Williams College": "williams.edu",
  "Wilmington College": "wilmington.edu",
  "Wilmington University": "wilmu.edu",
  "Wilson College": "warren-wilson.edu",
  "Wingate University": "wingate.edu",
  "Winona State University": "winona.edu",
  "Winston-Salem State University": "wssu.edu",
  "Winthrop University": "winthrop.edu",
  "Wisconsin Lutheran College": "wlc.edu",
  "Wittenberg University": "wittenberg.edu",
  "Wofford College": "wofford.edu",
  "Worcester Polytechnic Institute": "wpi.edu",
  "Wright State University": "wright.edu",
  "Xavier University": "xavier.edu",
  "Xavier University of Louisiana": "xula.edu",
  "Yale University": "yale.edu",
  "Yeshiva University": "yu.edu",
  "York College of Pennsylvania": "ycp.edu",
  "York College, City University of New York": "cityu.edu",
  "York University": "nyu.edu",
  "Young Harris College": "yhc.edu",
  "Youngstown State University": "ysu.edu",
};

export function collegeDomain(name: string): string | undefined {
  return COLLEGE_DOMAINS[name];
}
