// TEMPORARY mockup fixtures for customer preview screenshots. Removed after screenshot capture.
export const MOCK_USER = {
  id: "00000000-0000-0000-0000-000000000001",
  email: "demo@recruitinghub.app",
} as const;

export const MOCK_ATHLETES = [
  {
    id: "a1",
    full_name: "Jalen Carter",
    hometown: "Wichita, KS",
    state: "KS",
    high_school: "Wichita East HS",
    grad_year: 2027,
    position: "PG",
    height_inches: 74,
    weight_lbs: 175,
    jersey_number: 3,
    gpa: 3.8,
    sat_score: 1320,
    act_score: null,
    intended_major: "Business",
    instagram_handle: "jalen.hoops",
    tiktok_handle: null,
    bio: "Combo guard with a quick first step. Led team to MAYB regional final in 2025.",
    profile_photo_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "a2",
    full_name: "Marcus Reed",
    hometown: "Kansas City, MO",
    state: "MO",
    high_school: "Rockhurst",
    grad_year: 2026,
    position: "SF",
    height_inches: 78,
    weight_lbs: 200,
    jersey_number: 23,
    gpa: 3.6,
    sat_score: null,
    act_score: 28,
    intended_major: "Kinesiology",
    instagram_handle: null,
    tiktok_handle: null,
    bio: "",
    profile_photo_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "a3",
    full_name: "Devin Alvarez",
    hometown: "Oklahoma City, OK",
    state: "OK",
    high_school: "Bishop McGuinness",
    grad_year: 2027,
    position: "C",
    height_inches: 81,
    weight_lbs: 225,
    jersey_number: 42,
    gpa: 3.9,
    sat_score: 1410,
    act_score: null,
    intended_major: "Engineering",
    instagram_handle: "d.alvarez",
    tiktok_handle: null,
    bio: "",
    profile_photo_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "a4",
    full_name: "Tyler Brooks",
    hometown: "Tulsa, OK",
    state: "OK",
    high_school: "Union HS",
    grad_year: 2026,
    position: "SG",
    height_inches: 75,
    weight_lbs: 180,
    jersey_number: 11,
    gpa: 3.4,
    sat_score: null,
    act_score: 26,
    intended_major: "Communications",
    instagram_handle: null,
    tiktok_handle: null,
    bio: "",
    profile_photo_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "a5",
    full_name: "Andre Johnson",
    hometown: "Omaha, NE",
    state: "NE",
    high_school: "Creighton Prep",
    grad_year: 2028,
    position: "PF",
    height_inches: 79,
    weight_lbs: 210,
    jersey_number: 32,
    gpa: 3.7,
    sat_score: 1290,
    act_score: null,
    intended_major: "Undecided",
    instagram_handle: null,
    tiktok_handle: null,
    bio: "",
    profile_photo_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "a6",
    full_name: "Chris Nguyen",
    hometown: "Des Moines, IA",
    state: "IA",
    high_school: "Valley HS",
    grad_year: 2027,
    position: "PG",
    height_inches: 72,
    weight_lbs: 165,
    jersey_number: 5,
    gpa: 4.0,
    sat_score: 1480,
    act_score: null,
    intended_major: "Computer Science",
    instagram_handle: null,
    tiktok_handle: null,
    bio: "",
    profile_photo_url: null,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_VIDEOS = [
  { id: "v1", athlete_id: "a1", title: "2025 MAYB Nationals Highlights", provider: "youtube", url: "https://youtube.com/watch?v=x" },
  { id: "v2", athlete_id: "a1", title: "Junior Year Season Mix", provider: "hudl", url: "https://hudl.com/x" },
];

export const MOCK_EVENTS = [
  { id: "e1", athlete_id: "a1", title: "MAYB Summer Kickoff", event_date: "2026-08-15", location: "Wichita, KS", opponent: "KC Elite" },
  { id: "e2", athlete_id: "a1", title: "MAYB Nationals Pool Play", event_date: "2026-07-22", location: "OKC, OK", opponent: "Tulsa Storm" },
];

export const MOCK_COACH_REQUESTS = [
  {
    id: "r1",
    user_id: "u1",
    full_name: "Coach Miller",
    email: "miller@ksu.edu",
    college: "Kansas State University",
    title: "Assistant Coach",
    message: "Would love access to scout Midwest talent.",
    status: "pending",
    created_at: new Date().toISOString(),
    reviewed_at: null,
  },
  {
    id: "r2",
    user_id: "u2",
    full_name: "Coach Reeves",
    email: "reeves@ou.edu",
    college: "University of Oklahoma",
    title: "Recruiting Coordinator",
    message: "",
    status: "approved",
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    reviewed_at: new Date().toISOString(),
  },
];
