/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoachesIndexRouteImport } from './routes/_authenticated/coaches.index'
import { Route as AuthenticatedProfileEditRouteImport } from './routes/_authenticated/profile.edit'
import { Route as AuthenticatedCoachesSavedRouteImport } from './routes/_authenticated/coaches.saved'
import { Route as AuthenticatedAdminCoachRequestsRouteImport } from './routes/_authenticated/admin.coach-requests'
import { Route as AuthenticatedAAthleteIdRouteImport } from './routes/_authenticated/a.$athleteId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachesIndexRoute =
  AuthenticatedCoachesIndexRouteImport.update({
    id: '/coaches/',
    path: '/coaches/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileEditRoute =
  AuthenticatedProfileEditRouteImport.update({
    id: '/profile/edit',
    path: '/profile/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoachesSavedRoute =
  AuthenticatedCoachesSavedRouteImport.update({
    id: '/coaches/saved',
    path: '/coaches/saved',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCoachRequestsRoute =
  AuthenticatedAdminCoachRequestsRouteImport.update({
    id: '/admin/coach-requests',
    path: '/admin/coach-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAAthleteIdRoute = AuthenticatedAAthleteIdRouteImport.update({
  id: '/a/$athleteId',
  path: '/a/$athleteId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/a/$athleteId': typeof AuthenticatedAAthleteIdRoute
  '/admin/coach-requests': typeof AuthenticatedAdminCoachRequestsRoute
  '/coaches/saved': typeof AuthenticatedCoachesSavedRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/coaches/': typeof AuthenticatedCoachesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/a/$athleteId': typeof AuthenticatedAAthleteIdRoute
  '/admin/coach-requests': typeof AuthenticatedAdminCoachRequestsRoute
  '/coaches/saved': typeof AuthenticatedCoachesSavedRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/coaches': typeof AuthenticatedCoachesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/a/$athleteId': typeof AuthenticatedAAthleteIdRoute
  '/_authenticated/admin/coach-requests': typeof AuthenticatedAdminCoachRequestsRoute
  '/_authenticated/coaches/saved': typeof AuthenticatedCoachesSavedRoute
  '/_authenticated/profile/edit': typeof AuthenticatedProfileEditRoute
  '/_authenticated/coaches/': typeof AuthenticatedCoachesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/a/$athleteId'
    | '/admin/coach-requests'
    | '/coaches/saved'
    | '/profile/edit'
    | '/coaches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/a/$athleteId'
    | '/admin/coach-requests'
    | '/coaches/saved'
    | '/profile/edit'
    | '/coaches'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/a/$athleteId'
    | '/_authenticated/admin/coach-requests'
    | '/_authenticated/coaches/saved'
    | '/_authenticated/profile/edit'
    | '/_authenticated/coaches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coaches/': {
      id: '/_authenticated/coaches/'
      path: '/coaches'
      fullPath: '/coaches/'
      preLoaderRoute: typeof AuthenticatedCoachesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/edit': {
      id: '/_authenticated/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedProfileEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coaches/saved': {
      id: '/_authenticated/coaches/saved'
      path: '/coaches/saved'
      fullPath: '/coaches/saved'
      preLoaderRoute: typeof AuthenticatedCoachesSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/coach-requests': {
      id: '/_authenticated/admin/coach-requests'
      path: '/admin/coach-requests'
      fullPath: '/admin/coach-requests'
      preLoaderRoute: typeof AuthenticatedAdminCoachRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/a/$athleteId': {
      id: '/_authenticated/a/$athleteId'
      path: '/a/$athleteId'
      fullPath: '/a/$athleteId'
      preLoaderRoute: typeof AuthenticatedAAthleteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAAthleteIdRoute: typeof AuthenticatedAAthleteIdRoute
  AuthenticatedAdminCoachRequestsRoute: typeof AuthenticatedAdminCoachRequestsRoute
  AuthenticatedCoachesSavedRoute: typeof AuthenticatedCoachesSavedRoute
  AuthenticatedProfileEditRoute: typeof AuthenticatedProfileEditRoute
  AuthenticatedCoachesIndexRoute: typeof AuthenticatedCoachesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAAthleteIdRoute: AuthenticatedAAthleteIdRoute,
  AuthenticatedAdminCoachRequestsRoute: AuthenticatedAdminCoachRequestsRoute,
  AuthenticatedCoachesSavedRoute: AuthenticatedCoachesSavedRoute,
  AuthenticatedProfileEditRoute: AuthenticatedProfileEditRoute,
  AuthenticatedCoachesIndexRoute: AuthenticatedCoachesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
