/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AAthleteIdRouteImport } from './routes/a.$athleteId'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedFamilyRouteImport } from './routes/_authenticated/family'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCollegesRouteImport } from './routes/_authenticated/colleges'
import { Route as AuthenticatedCoachesIndexRouteImport } from './routes/_authenticated/coaches.index'
import { Route as AuthenticatedProfileEditRouteImport } from './routes/_authenticated/profile.edit'
import { Route as AuthenticatedCoachesSavedRouteImport } from './routes/_authenticated/coaches.saved'
import { Route as AuthenticatedCoachesMessagesRouteImport } from './routes/_authenticated/coaches.messages'
import { Route as AuthenticatedCoachesGamesRouteImport } from './routes/_authenticated/coaches.games'
import { Route as AuthenticatedAdminCoachRequestsRouteImport } from './routes/_authenticated/admin.coach-requests'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AAthleteIdRoute = AAthleteIdRouteImport.update({
  id: '/a/$athleteId',
  path: '/a/$athleteId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamilyRoute = AuthenticatedFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollegesRoute = AuthenticatedCollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachesIndexRoute =
  AuthenticatedCoachesIndexRouteImport.update({
    id: '/coaches/',
    path: '/coaches/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileEditRoute =
  AuthenticatedProfileEditRouteImport.update({
    id: '/profile/edit',
    path: '/profile/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoachesSavedRoute =
  AuthenticatedCoachesSavedRouteImport.update({
    id: '/coaches/saved',
    path: '/coaches/saved',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoachesMessagesRoute =
  AuthenticatedCoachesMessagesRouteImport.update({
    id: '/coaches/messages',
    path: '/coaches/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoachesGamesRoute =
  AuthenticatedCoachesGamesRouteImport.update({
    id: '/coaches/games',
    path: '/coaches/games',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCoachRequestsRoute =
  AuthenticatedAdminCoachRequestsRouteImport.update({
    id: '/admin/coach-requests',
    path: '/admin/coach-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/colleges': typeof AuthenticatedCollegesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/a/$athleteId': typeof AAthleteIdRoute
  '/admin/coach-requests': typeof AuthenticatedAdminCoachRequestsRoute
  '/coaches/games': typeof AuthenticatedCoachesGamesRoute
  '/coaches/messages': typeof AuthenticatedCoachesMessagesRoute
  '/coaches/saved': typeof AuthenticatedCoachesSavedRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/coaches/': typeof AuthenticatedCoachesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/colleges': typeof AuthenticatedCollegesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/a/$athleteId': typeof AAthleteIdRoute
  '/admin/coach-requests': typeof AuthenticatedAdminCoachRequestsRoute
  '/coaches/games': typeof AuthenticatedCoachesGamesRoute
  '/coaches/messages': typeof AuthenticatedCoachesMessagesRoute
  '/coaches/saved': typeof AuthenticatedCoachesSavedRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/coaches': typeof AuthenticatedCoachesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/colleges': typeof AuthenticatedCollegesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/family': typeof AuthenticatedFamilyRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/a/$athleteId': typeof AAthleteIdRoute
  '/_authenticated/admin/coach-requests': typeof AuthenticatedAdminCoachRequestsRoute
  '/_authenticated/coaches/games': typeof AuthenticatedCoachesGamesRoute
  '/_authenticated/coaches/messages': typeof AuthenticatedCoachesMessagesRoute
  '/_authenticated/coaches/saved': typeof AuthenticatedCoachesSavedRoute
  '/_authenticated/profile/edit': typeof AuthenticatedProfileEditRoute
  '/_authenticated/coaches/': typeof AuthenticatedCoachesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/colleges'
    | '/dashboard'
    | '/family'
    | '/insights'
    | '/messages'
    | '/a/$athleteId'
    | '/admin/coach-requests'
    | '/coaches/games'
    | '/coaches/messages'
    | '/coaches/saved'
    | '/profile/edit'
    | '/coaches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/colleges'
    | '/dashboard'
    | '/family'
    | '/insights'
    | '/messages'
    | '/a/$athleteId'
    | '/admin/coach-requests'
    | '/coaches/games'
    | '/coaches/messages'
    | '/coaches/saved'
    | '/profile/edit'
    | '/coaches'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/colleges'
    | '/_authenticated/dashboard'
    | '/_authenticated/family'
    | '/_authenticated/insights'
    | '/_authenticated/messages'
    | '/a/$athleteId'
    | '/_authenticated/admin/coach-requests'
    | '/_authenticated/coaches/games'
    | '/_authenticated/coaches/messages'
    | '/_authenticated/coaches/saved'
    | '/_authenticated/profile/edit'
    | '/_authenticated/coaches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  AAthleteIdRoute: typeof AAthleteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$athleteId': {
      id: '/a/$athleteId'
      path: '/a/$athleteId'
      fullPath: '/a/$athleteId'
      preLoaderRoute: typeof AAthleteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family': {
      id: '/_authenticated/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof AuthenticatedFamilyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colleges': {
      id: '/_authenticated/colleges'
      path: '/colleges'
      fullPath: '/colleges'
      preLoaderRoute: typeof AuthenticatedCollegesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coaches/': {
      id: '/_authenticated/coaches/'
      path: '/coaches'
      fullPath: '/coaches/'
      preLoaderRoute: typeof AuthenticatedCoachesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/edit': {
      id: '/_authenticated/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedProfileEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coaches/saved': {
      id: '/_authenticated/coaches/saved'
      path: '/coaches/saved'
      fullPath: '/coaches/saved'
      preLoaderRoute: typeof AuthenticatedCoachesSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coaches/messages': {
      id: '/_authenticated/coaches/messages'
      path: '/coaches/messages'
      fullPath: '/coaches/messages'
      preLoaderRoute: typeof AuthenticatedCoachesMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coaches/games': {
      id: '/_authenticated/coaches/games'
      path: '/coaches/games'
      fullPath: '/coaches/games'
      preLoaderRoute: typeof AuthenticatedCoachesGamesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/coach-requests': {
      id: '/_authenticated/admin/coach-requests'
      path: '/admin/coach-requests'
      fullPath: '/admin/coach-requests'
      preLoaderRoute: typeof AuthenticatedAdminCoachRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCollegesRoute: typeof AuthenticatedCollegesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFamilyRoute: typeof AuthenticatedFamilyRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedAdminCoachRequestsRoute: typeof AuthenticatedAdminCoachRequestsRoute
  AuthenticatedCoachesGamesRoute: typeof AuthenticatedCoachesGamesRoute
  AuthenticatedCoachesMessagesRoute: typeof AuthenticatedCoachesMessagesRoute
  AuthenticatedCoachesSavedRoute: typeof AuthenticatedCoachesSavedRoute
  AuthenticatedProfileEditRoute: typeof AuthenticatedProfileEditRoute
  AuthenticatedCoachesIndexRoute: typeof AuthenticatedCoachesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCollegesRoute: AuthenticatedCollegesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFamilyRoute: AuthenticatedFamilyRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedAdminCoachRequestsRoute: AuthenticatedAdminCoachRequestsRoute,
  AuthenticatedCoachesGamesRoute: AuthenticatedCoachesGamesRoute,
  AuthenticatedCoachesMessagesRoute: AuthenticatedCoachesMessagesRoute,
  AuthenticatedCoachesSavedRoute: AuthenticatedCoachesSavedRoute,
  AuthenticatedProfileEditRoute: AuthenticatedProfileEditRoute,
  AuthenticatedCoachesIndexRoute: AuthenticatedCoachesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  AAthleteIdRoute: AAthleteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
